
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

export const assetFolders = {
  /**
   * Articles
   */
  articles_f253858: {
    name: "Articles",
    codename: "articles_f253858",
    id: "f2538584-be2d-5af0-b955-bafe16b54f27",
    externalId: "articles-e1858af8-4ae9-414f-ba1c-18c557c69ee8",
    folders: {},
  },

  /**
   * Solutions
   */
  solutions: {
    name: "Solutions",
    codename: "solutions",
    id: "ac4e75d7-11a3-52de-a801-7412720935ff",
    externalId: "solutions-d414f725-9ce0-4883-ac87-7e05d1530b08",
    folders: {},
  },

  /**
   * People
   */
  people_13343d3: {
    name: "People",
    codename: "people_13343d3",
    id: "13343d3c-aa63-5d21-a836-17a690f51855",
    externalId: "people-16c463d4-3c7c-43e9-8ce1-5d6cef7be232",
    folders: {},
  },

  /**
   * Guidelines
   */
  guidelines_3cdf1ec: {
    name: "Guidelines",
    codename: "guidelines_3cdf1ec",
    id: "3cdf1ec9-d786-5411-9d9b-8e74dd54024e",
    externalId: "guidelines-67080809-dd53-435d-80e9-4af8bf1d74f3",
    folders: {},
  },

  /**
   * Products
   */
  products: {
    name: "Products",
    codename: "products",
    id: "4b2d9d85-213c-57d8-bc9b-af51f8cd4eb6",
    externalId: "products-bccfae97-36fb-4d15-9888-f0c14076dfbd",
    folders: {},
  },

  /**
   * Landing Page
   */
  landing_page: {
    name: "Landing Page",
    codename: "landing_page",
    id: "6a9ab183-5106-5359-8f54-f04081ff9bad",
    externalId: "landingPage-89a8c0fb-d1d4-4412-9bf9-c3a6ef26db82",
    folders: {
      /**
       * Hero Images
       */
      hero_images_42f5839: {
        name: "Hero Images",
        codename: "hero_images_42f5839",
        id: "42f58392-bbfb-5ae3-b662-161720d4f006",
        externalId: "heroImages-c74ceb8a-d8b7-400a-9cbc-f0f2f0e1841e",
        folders: {},
      },
    },
  },
} as const;
