
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

export const collections = {
  /**
   * Ficto Healthtech
   */
  ficto_healthtech: {
    codename: "ficto_healthtech",
    id: "5eb3c621-9492-524e-a061-9ee80bbfc947",
    name: "Ficto Healthtech",
  },

  /**
   * Ficto Imaging
   */
  ficto_imaging: {
    codename: "ficto_imaging",
    id: "883baa53-543d-5557-bf4d-1dc7c59993e1",
    name: "Ficto Imaging",
  },

  /**
   * Ficto Surgical
   */
  ficto_surgical: {
    codename: "ficto_surgical",
    id: "47ff7979-f3b7-5492-be72-e6f5a9e73d0f",
    name: "Ficto Surgical",
  },

  /**
   * Common
   */
  default: {
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
    name: "Common",
  },
} as const;
