
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

export const contentTypeSnippets = {
  /**
   * 💡 Spotlight guidelines
   */
  spotlight_guidelines: {
    name: "💡 Spotlight guidelines",
    codename: "spotlight_guidelines",
    id: "b0299f53-78b4-5c20-bbf3-7cc9129cdb12",
    externalId: "spotlightGuidelines-367e017c-5b46-471f-8da0-4baa6f249dc8",
    elements: {},
  },

  /**
   * Metadata
   */
  metadata: {
    name: "Metadata",
    codename: "metadata",
    id: "754cddda-44fc-590c-8663-a647690851d9",
    externalId: "metadata-f8bd5c13-547c-47f6-966d-7f33a6b24e10",
    elements: {
      /**
       * Title (text)
       */
      metadata__title: {
        name: "Title",
        codename: "metadata__title",
        id: "49abab33-e5d1-55bb-9c1b-2f144430da28",
        externalId: "title-28c35ddc-2478-4026-ac5c-84a102ec9a3e",
        required: false,
        type: "text",
      },

      /**
       * Description (text)
       */
      metadata__description: {
        name: "Description",
        codename: "metadata__description",
        id: "e57614c6-e299-51c3-83bc-961f053dfe17",
        externalId: "description-3fcbbc28-52f7-4691-9e16-56c6bc4555bb",
        required: false,
        type: "text",
      },

      /**
       * Keywords (text)
       * Guidelines: Keywords should be separated by delimiter ","
       */
      metadata__keywords: {
        name: "Keywords",
        codename: "metadata__keywords",
        id: "f46d7c9a-a08f-5987-83e7-a061dd036842",
        externalId: "keywords-8c99c0f7-87ed-4df9-86db-34e112e3b3c9",
        required: false,
        type: "text",
      },
    },
  },

  /**
   * Reference
   */
  reference: {
    name: "Reference",
    codename: "reference",
    id: "6761a539-765f-5bff-a370-f2f4bff66eb4",
    externalId: "reference-3652c986-423b-4952-aec4-cfd47087bd5c",
    elements: {
      /**
       * Label (text)
       */
      reference__label: {
        name: "Label",
        codename: "reference__label",
        id: "15ee4053-00fd-5d5e-a2d7-4437079251ce",
        externalId: "label-6a1dec94-5127-4d8f-908c-3c0aedbe1f5b",
        required: false,
        type: "text",
      },

      /**
       * Caption (text)
       */
      reference__caption: {
        name: "Caption",
        codename: "reference__caption",
        id: "75684270-5e43-5d21-b93a-700f85e50853",
        externalId: "caption-7983245f-e1fc-4ed0-a185-f064e82cf5c7",
        required: false,
        type: "text",
      },

      /**
       * External URI (text)
       * Guidelines: Link to an external resource, has higher resolution priority than item link.
       */
      reference__external_uri: {
        name: "External URI",
        codename: "reference__external_uri",
        id: "580e3f46-f033-50d4-9f34-4ed91384f4e4",
        externalId: "externalURI-2d6525cc-0fe7-4c3e-8ebe-357711715c60",
        required: false,
        type: "text",
      },

      /**
       * Content item link (modular_content)
       * Guidelines: Link to a supported content item, resolution can vary based on presentation layer.
       */
      reference__content__item_link: {
        name: "Content item link",
        codename: "reference__content__item_link",
        id: "ed9d88d5-2375-57c3-9916-615eaae7d5da",
        externalId: "contentItemLink-5f68c354-0d2e-472d-a2a6-fdc928c55d97",
        required: false,
        type: "modular_content",
      },
    },
  },

  /**
   * 🧩 Component guidelines
   */
  component_guidelines: {
    name: "🧩 Component guidelines",
    codename: "component_guidelines",
    id: "40f2499f-6de6-5713-b1f9-2eb50d49d88c",
    externalId: "componentGuidelines-b819d57b-85fa-451a-964d-1c9ea1433b25",
    elements: {},
  },

  /**
   * Product base
   */
  product_base: {
    name: "Product base",
    codename: "product_base",
    id: "93c26558-f7e5-57ea-802f-5f1f079ea7a9",
    externalId: "productBase-38a81bf0-6312-405b-b939-59a483c9be53",
    elements: {
      /**
       * Name (text)
       * Guidelines: Include key product attributes, such as brand name or model.
       */
      product_base__name: {
        name: "Name",
        codename: "product_base__name",
        id: "9647f1cc-3870-5b67-874b-d56fc2abd7ad",
        externalId: "name-3e01f16b-562a-4b2d-8f56-9fe1182b0a12",
        required: true,
        type: "text",
      },

      /**
       * Description (text)
       */
      product_base__description: {
        name: "Description",
        codename: "product_base__description",
        id: "30f6b775-071e-5a5a-9394-8251d2081b0e",
        externalId: "description-518d3ce8-be95-4c92-bc17-5415e7d51896",
        required: false,
        type: "text",
      },

      /**
       * Main image (asset)
       */
      product_base__main_image: {
        name: "Main image",
        codename: "product_base__main_image",
        id: "333cb56d-09c7-58a9-b759-97a0931ce8e6",
        externalId: "mainImage-7c02a80f-924e-459c-8e00-6486cf14a470",
        required: false,
        type: "asset",
      },
    },
  },

  /**
   * 🧱 Block guidelines
   */
  block_guidelines: {
    name: "🧱 Block guidelines",
    codename: "block_guidelines",
    id: "0b86d622-6911-52d9-a8c0-a3638dd0243c",
    externalId: "blockGuidelines-3d3c7579-a51e-4e27-af53-cff820baf85a",
    elements: {},
  },
} as const;
