
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

export const languages = {
  /**
   * Default project language
   */
  default: {
    name: "Default project language",
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
    isActive: true,
    isDefault: true,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
  },
} as const;
