
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

export const taxonomies = {
  /**
   * imaging_technology
   */
  imaging_technology: {
    name: "Imaging technology",
    codename: "imaging_technology",
    externalId: "imagingTechnology-408747da-d8b7-49ad-976d-50646d0a47d3",
    id: "5cf829cd-e8fe-56c2-89be-369de0a0b8ff",
    terms: {
      /**
       * MRI
       */
      mri: {
        codename: "mri",
        id: "8c38582f-fb7d-5d14-8edd-f403329bbfe7",
        externalId: "mri-e71389d4-f293-4e1d-8022-48b18847804c",
        name: "MRI",
        terms: {},
      },

      /**
       * PET
       */
      pet: {
        codename: "pet",
        id: "1305872b-c9f9-5b18-b709-ae41c15455f0",
        externalId: "pet-c77778ce-23b3-4cf4-ba39-af75aa3d5960",
        name: "PET",
        terms: {},
      },

      /**
       * X-Ray
       */
      x_ray: {
        codename: "x_ray",
        id: "9eb5bb30-eb0d-5a0e-8a89-95c2032f8747",
        externalId: "xray-ded621be-4bad-4636-9a37-4be8cb707eb3",
        name: "X-Ray",
        terms: {},
      },
    },
  },

  /**
   * article_type
   */
  article_type: {
    name: "Article type",
    codename: "article_type",
    externalId: "articleType-d73a0b57-78c1-442f-9d2b-300f2139b241",
    id: "37f4ed63-efb5-54cb-8cc9-4fdf63223f1e",
    terms: {
      /**
       * Blog post
       */
      post: {
        codename: "post",
        id: "934255d5-c81f-53a8-b183-3cc3cb3ca8e7",
        externalId: "blogPost-36a23560-d3e8-4c02-8ed2-6963e6e59b1c",
        name: "Blog post",
        terms: {},
      },

      /**
       * Industry news
       */
      news: {
        codename: "news",
        id: "b807df5d-0e92-5039-8757-055630182cd9",
        externalId: "industryNews-6edb577a-1401-4106-9a22-d531bbc62d94",
        name: "Industry news",
        terms: {},
      },
    },
  },

  /**
   * product_category
   */
  product_category: {
    name: "Product category",
    codename: "product_category",
    externalId: "productCategory-9b5d98d7-2130-4d94-a47f-5fb6912bb414",
    id: "502de9a1-3673-51e5-bf88-92e76c35cbee",
    terms: {
      /**
       * Cutting
       */
      cutting: {
        codename: "cutting",
        id: "4118aa3b-faae-5984-a57c-1beb3ce66bd9",
        externalId: "cutting-26799a13-dca8-4714-9a72-48739ae27f3a",
        name: "Cutting",
        terms: {},
      },

      /**
       * Retracting
       */
      retracting: {
        codename: "retracting",
        id: "9173ff63-9370-5e14-86a7-83b23075703b",
        externalId: "retracting-da9edb2e-a724-4b0a-8903-2bf8db1c7c45",
        name: "Retracting",
        terms: {
          /**
           * Hand held
           */
          hand_held: {
            codename: "hand_held",
            id: "562bfc38-6d54-5d5b-a303-6602b7b54a66",
            externalId: "handHeld-1f802ab8-7826-4bf6-a206-a9df539f7ef9",
            name: "Hand held",
            terms: {},
          },

          /**
           * Self retaining
           */
          self_retaining: {
            codename: "self_retaining",
            id: "7b0639df-03e0-5bf8-b15f-a8d11bd52763",
            externalId: "selfRetaining-0ff11769-f10f-4ea1-af5b-8c1e624e82e3",
            name: "Self retaining",
            terms: {},
          },
        },
      },

      /**
       * Grasping
       */
      grasping: {
        codename: "grasping",
        id: "ebdb0e8c-d4f7-54c8-a507-f5b1979d5899",
        externalId: "grasping-fca80970-ba27-4ac4-8361-abdf20ffe421",
        name: "Grasping",
        terms: {},
      },
    },
  },

  /**
   * fact_type
   */
  fact_type: {
    name: "Fact type",
    codename: "fact_type",
    externalId: "factType-0910c76d-6d61-49a4-bb12-6aa850c2938e",
    id: "60c8d377-24b2-54f0-886b-18aaa0f1095b",
    terms: {
      /**
       * Card
       */
      card: {
        codename: "card",
        id: "29a4cb84-658a-5cd2-84e8-686a1cced573",
        externalId: "card-26db0171-09f9-4993-b69f-814198da514b",
        name: "Card",
        terms: {},
      },

      /**
       * Hero unit
       */
      hero_unit: {
        codename: "hero_unit",
        id: "d15ad24b-2aa7-5e31-a40c-ac1d58557fde",
        externalId: "heroUnit-d1a6ac61-3679-4b5b-b295-b2434d3c539b",
        name: "Hero unit",
        terms: {},
      },

      /**
       * Milestone
       */
      milestone: {
        codename: "milestone",
        id: "460cbbf6-fbf4-574c-b5dc-f62af666d3ea",
        externalId: "milestone-2a85f3ef-0cde-480e-b1c5-aab66a8d40cf",
        name: "Milestone",
        terms: {},
      },

      /**
       * Testimonial
       */
      testimonial: {
        codename: "testimonial",
        id: "5dad70ce-1e17-56e6-ab65-fd0556cccc19",
        externalId: "testimonial-380f0696-226f-4389-9135-25d522dfd5c8",
        name: "Testimonial",
        terms: {},
      },
    },
  },
} as const;
