
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type {
  IContentItem,
  IContentItemElements,
} from "@kontent-ai/delivery-sdk";
import type {
  ContentTypeCodenames,
  CollectionCodenames,
  LanguageCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames,
} from "./delivery.codenames.ts";

/**
 * Core content type used in favor of generic 'IContentItem'
 */
export type CoreContentType<
  TElements extends IContentItemElements = IContentItemElements,
  TContentTypeCodename extends ContentTypeCodenames = ContentTypeCodenames,
> = IContentItem<
  TElements,
  TContentTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;
