
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = "default";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "person"
  | "article"
  | "navigation_item"
  | "content_chunk"
  | "action"
  | "page"
  | "fact"
  | "callout"
  | "product"
  | "website_root"
  | "visual_container"
  | "solution";

/**
 * Type representing all collections
 */
export type CollectionCodenames =
  | "ficto_healthtech"
  | "ficto_imaging"
  | "ficto_surgical"
  | "default";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = "default";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "imaging_technology"
  | "article_type"
  | "product_category"
  | "fact_type";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
  | "draft"
  | "published"
  | "archived"
  | "scheduled";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "guidelines"
  | "photograph"
  | "first_name"
  | "last_name"
  | "occupation"
  | "bio"
  | "title"
  | "hero_image"
  | "abstract"
  | "type"
  | "publishing_date"
  | "content"
  | "author"
  | "slug"
  | "metadata"
  | "reference"
  | "subitems"
  | "block_guidelines"
  | "action_guidelines"
  | "image"
  | "spotlight_guidelines"
  | "n07e9edea_7327_434b_97b7_400f8d5cacf1"
  | "subpages"
  | "message"
  | "fact_type"
  | "component_guidelines"
  | "disclaimer_guidelines"
  | "product_guidelines"
  | "product_base"
  | "category"
  | "price"
  | "f870bcac_ef52_4f4e_b369_2c2c104bce8c"
  | "navigation"
  | "subtitle"
  | "items"
  | "visual_representation"
  | "n57e24022_8b5a_4b98_821e_97217a884dcc"
  | "imaging_technology"
  | "showcase"
  | "live_preview_guidelines__spotlight_guidelines__guidelines"
  | "metadata__guidelines"
  | "metadata__title"
  | "metadata__description"
  | "metadata__keywords"
  | "reference__label"
  | "reference__caption"
  | "reference__external_uri"
  | "reference__content__item_link"
  | "component_guidelines__guidelines"
  | "product_base__name"
  | "product_base__description"
  | "product_base__main_image"
  | "block_guidelines__guidelines";
