import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Achievement
 * Id: 59d408cc-299b-48d2-972b-22028e095963
 * Codename: achievement
 */
export type Achievement = IContentItem<{
  /**
   * Subtitle (text)
   * Required: true
   * Id: 7b04ac84-cdd9-4e30-b4f6-93ace70f4116
   * Codename: subtitle
   */
  subtitle: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: f49769f4-7688-4fee-94e4-16174c03e049
   * Codename: title
   */
  title: Elements.TextElement;
}>;
