import { type IContentItem } from '@kontent-ai/delivery-sdk';
import { type Reference } from '../content-type-snippets/reference';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Action
 * Id: ff3f3ef3-f658-4f6b-bbbd-230327878367
 * Codename: action
 */
export type Action = IContentItem<{}> & Reference;
