
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Reference } from "../content-type-snippets/index.ts";

/**
 * Action
 *
 * Id: 46d20e5c-a72c-5a48-bfae-b054632877ca
 * Codename: action
 */
export type Action = CoreContentType<
  {
    /**
     * Image
     *
     * Type: asset
     * Required: false
     * Codename: image
     * Id: bee5bc76-a644-546b-8e3b-e3b5c2dfe2c3
     */
    readonly image: Elements.AssetsElement;
  } & Reference,
  "action"
>;

/**
 * Type representing all available element codenames for Action
 */
export type ActionElementCodenames =
  | "reference__label"
  | "reference__caption"
  | "reference__external_uri"
  | "reference__content__item_link"
  | "image";

/**
 * Type guard for Action
 *
 * Id: 46d20e5c-a72c-5a48-bfae-b054632877ca
 * Codename: action
 */
export function isAction(
  item: CoreContentType | undefined | null,
): item is Action {
  return item?.system?.type === "action";
}
