import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Reference } from '../content-type-snippets/reference';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Action
 * Id: 32395d41-ee0d-499a-8cd6-23b3d9f267e9
 * Codename: action
 */
export type Action = IContentItem<{
    /**
     * Image (asset)
     * Required: false
     * Id: 452e8309-8387-410e-8a4f-18db9c98dd04
     * Codename: image
     */
    image: Elements.AssetsElement;
}> &
    Reference;
