import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ArticleType } from '../taxonomies/articleType';
import { type Metadata } from '../content-type-snippets/metadata';
import { type Person } from './person';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Article
 * Id: 5568750a-d7fd-51fa-a8bb-a08940ac5395
 * Codename: article
 */
export type Article = IContentItem<{
    /**
     * Abstract (text)
     * Required: false
     * Id: 5ae9979f-cc84-5c0b-81d8-65eabf11f2ec
     * Codename: abstract
     *
     * Don't make it too long. At this point users decides, whether they want to continue reading!
     */
    abstract: Elements.TextElement;

    /**
     * Author (modular_content)
     * Required: true
     * Id: 5be60600-49ac-52f8-a759-ab0ead3a3301
     * Codename: author
     */
    author: Elements.LinkedItemsElement<Person>;

    /**
     * Content (rich_text)
     * Required: true
     * Id: 7d4b95b0-76fc-552e-8931-c90dd2746399
     * Codename: content
     */
    content: Elements.RichTextElement;

    /**
     * Hero Image (asset)
     * Required: true
     * Id: ed868ae7-0b90-5752-a53b-aa4cfa2ca56e
     * Codename: hero_image
     */
    heroImage: Elements.AssetsElement;

    /**
     * Publishing date (date_time)
     * Required: true
     * Id: dba8efd9-052c-557a-9dfd-3f43f966eab8
     * Codename: publishing_date
     */
    publishingDate: Elements.DateTimeElement;

    /**
     * Slug (url_slug)
     * Required: true
     * Id: 7b9f3bb2-2efb-5285-8988-bfb66e45cf77
     * Codename: slug
     */
    slug: Elements.UrlSlugElement;

    /**
     * Title (text)
     * Required: true
     * Id: ae9be828-90fe-5fb4-ae3a-8dfe047e2567
     * Codename: title
     *
     * You can use online tools get score on your titles and incrementally improve it.
     */
    title: Elements.TextElement;

    /**
     * Article type (taxonomy)
     * Required: false
     * Id: cc163930-9863-47fb-b158-2d3c95c3990a
     * Codename: type
     *
     * Pick a suitable category for your article.
     */
    type: Elements.TaxonomyElement<ArticleType>;
}> &
    Metadata;
