
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { Action, Component_Callout, Person } from "./index.ts";
import type { ArticleType } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";

/**
 * Article
 *
 * Id: 5568750a-d7fd-51fa-a8bb-a08940ac5395
 * Codename: article
 */
export type Article = CoreContentType<
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: ae9be828-90fe-5fb4-ae3a-8dfe047e2567
     * Guidelines: You can use online tools get score on your titles and incrementally improve it.
     */
    readonly title: Elements.TextElement;
    /**
     * Hero Image
     *
     * Type: asset
     * Required: true
     * Codename: hero_image
     * Id: ed868ae7-0b90-5752-a53b-aa4cfa2ca56e
     */
    readonly hero_image: Elements.AssetsElement;
    /**
     * Abstract
     *
     * Type: text
     * Required: false
     * Codename: abstract
     * Id: 5ae9979f-cc84-5c0b-81d8-65eabf11f2ec
     * Guidelines: Don't make it too long. At this point users decides, whether they want to continue reading!
     */
    readonly abstract: Elements.TextElement;
    /**
     * Article type
     *
     * Type: taxonomy
     * Required: false
     * Codename: type
     * Id: c505fded-9c1f-5583-8cf2-dfa4763d2f2a
     * Guidelines: Pick a suitable category for your article.
     */
    readonly type: Elements.TaxonomyElement<ArticleType, "type">;
    /**
     * Publishing date
     *
     * Type: date_time
     * Required: true
     * Codename: publishing_date
     * Id: dba8efd9-052c-557a-9dfd-3f43f966eab8
     */
    readonly publishing_date: Elements.DateTimeElement;
    /**
     * Content
     *
     * Type: rich_text
     * Required: true
     * Codename: content
     * Id: 7d4b95b0-76fc-552e-8931-c90dd2746399
     */
    readonly content: Elements.RichTextElement<Action | Component_Callout>;
    /**
     * Author
     *
     * Type: modular_content
     * Required: true
     * Codename: author
     * Id: 5be60600-49ac-52f8-a759-ab0ead3a3301
     */
    readonly author: Elements.LinkedItemsElement<Person>;
    /**
     * Slug
     *
     * Type: url_slug
     * Required: true
     * Codename: slug
     * Id: 7b9f3bb2-2efb-5285-8988-bfb66e45cf77
     */
    readonly slug: Elements.UrlSlugElement;
  } & Metadata,
  "article"
>;

/**
 * Type representing all available element codenames for Article
 */
export type ArticleElementCodenames =
  | "title"
  | "hero_image"
  | "abstract"
  | "type"
  | "publishing_date"
  | "content"
  | "author"
  | "slug"
  | "metadata__title"
  | "metadata__description"
  | "metadata__keywords";

/**
 * Type guard for Article
 *
 * Id: 5568750a-d7fd-51fa-a8bb-a08940ac5395
 * Codename: article
 */
export function isArticle(
  item: CoreContentType | undefined | null,
): item is Article {
  return item?.system?.type === "article";
}
