import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Fact } from './fact';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Hero unit
 * Id: 76f5b7c0-3d2d-40d9-a5a9-3e4d8ec71a54
 * Codename: hero_unit
 */
export type Block_HeroUnit = IContentItem<{
  /**
   * Background image (asset)
   * Required: false
   * Id: f00f8f79-3a3b-4098-8143-c52f0804f27b
   * Codename: background_image
   */
  backgroundImage: Elements.AssetsElement;

  /**
   * Fact (modular_content)
   * Required: true
   * Id: 65599bd5-4e31-41fa-926f-d140b07ae404
   * Codename: fact
   */
  fact: Elements.LinkedItemsElement<Fact>;

  /**
   * Target (text)
   * Required: false
   * Id: 6524fba0-7e7a-462e-bfc0-58b5bd0cce24
   * Codename: target
   */
  target: Elements.TextElement;
}>;
