import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Milestone } from './milestone';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Grid
 * Id: 6f83adaa-788a-4778-8ed6-b64d73d54cff
 * Codename: grid
 */
export type Block_Grid = IContentItem<{
  /**
   * Grid items (modular_content)
   * Required: false
   * Id: 43fad747-0fac-4559-a0e4-9b1576eff9e7
   * Codename: grid_items
   */
  gridItems: Elements.LinkedItemsElement<Milestone>;
}>;
