import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_VisualComponentGuidelines } from '../content-type-snippets/Block_VisualComponentGuidelines';
import { type Fact } from './fact';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Visual container
 * Id: e23c2808-d953-5914-a526-ab702cc519f5
 * Codename: visual_container
 */
export type Block_VisualContainer = IContentItem<{
  /**
   * Items (modular_content)
   * Required: true
   * Id: 081f63c6-9589-5f8d-a9de-bc3b1ceb24e7
   * Codename: items
   */
  items: Elements.LinkedItemsElement<Fact>;

  /**
   * Subtitle (text)
   * Required: false
   * Id: db1dcba9-ffde-5ff9-a8dc-e594cf3d27d8
   * Codename: subtitle
   */
  subtitle: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 22e19c4d-aeeb-5c87-852c-b8a8202dfbad
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * Visual representation (multiple_choice)
   * Required: true
   * Id: 2c3d8fe4-a21d-524a-aba5-5fd1913f8341
   * Codename: visual_representation
   *
   * ⚠ You should try to avoid including visual information in the content. This is one of the edge cases that might be viable since this content type is used for website representation only.
   */
  visualRepresentation: Elements.MultipleChoiceElement;
}> &
  Block_VisualComponentGuidelines;
