import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Content chunk
 * Id: 7d315973-6157-4b4b-b722-0674b16121bf
 * Codename: content_chunk
 */
export type Block_ContentChunk = IContentItem<{
  /**
   * Content (rich_text)
   * Required: false
   * Id: f7e1a1d0-f3cb-42f8-b7b1-4005fae328d0
   * Codename: content
   */
  content: Elements.RichTextElement;
}>;
