import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_CallToAction } from './Block_CallToAction';
import { type Block_HeroUnit } from './Block_HeroUnit';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Carousel
 * Id: f1e220f9-76af-4c78-8137-e2bfa026e320
 * Codename: carousel
 */
export type Block_Carousel = IContentItem<{
  /**
   * Elements (modular_content)
   * Required: true
   * Id: fb6b765a-1d09-4d98-81db-66bc3a63c487
   * Codename: elements
   */
  elements: Elements.LinkedItemsElement<Block_HeroUnit | Block_CallToAction>;
}>;
