import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_BlockGuidelines } from '../content-type-snippets/Block_BlockGuidelines';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Content chunk
 * Id: 77194b36-3971-5137-b0d8-8dbed2b4b18a
 * Codename: content_chunk
 */
export type Block_ContentChunk = IContentItem<{
  /**
   * Content (rich_text)
   * Required: false
   * Id: 7ace9f5a-cf40-5339-8122-2f320ba3326e
   * Codename: content
   */
  content: Elements.RichTextElement;
}> &
  Block_BlockGuidelines;
