import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type GenericAction } from './genericAction';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Call to action
 * Id: 11c3fbcd-2de0-4f56-96e5-f080bb9a28d1
 * Codename: call_to_action
 */
export type Block_CallToAction = IContentItem<{
  /**
   * Action (modular_content)
   * Required: true
   * Id: 1d6a4e9b-29b3-4f62-a418-278bc71c3f9c
   * Codename: action
   */
  action: Elements.LinkedItemsElement<GenericAction>;

  /**
   * Subtitle (text)
   * Required: false
   * Id: 1feb250b-c828-4b32-9196-d70d66b84bd9
   * Codename: subtitle
   */
  subtitle: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: 2a1e51f1-3128-4321-8cf5-38e821712af0
   * Codename: title
   */
  title: Elements.TextElement;
}>;
