
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { Component_Callout, Action } from "./index.ts";
import type { CoreContentType } from "../system/index.ts";

/**
 * 🧱 Content chunk
 *
 * Id: aaca014e-ca52-5543-b8fc-76509b245e87
 * Codename: content_chunk
 */
export type Block_ContentChunk = CoreContentType<
  {
    /**
     * Content
     *
     * Type: rich_text
     * Required: false
     * Codename: content
     * Id: b60790f9-7ed1-5b6d-92ed-15594b9e4253
     */
    readonly content: Elements.RichTextElement<Component_Callout | Action>;
  },
  "content_chunk"
>;

/**
 * Type representing all available element codenames for 🧱 Content chunk
 */
export type Block_ContentChunkElementCodenames = "content";

/**
 * Type guard for 🧱 Content chunk
 *
 * Id: aaca014e-ca52-5543-b8fc-76509b245e87
 * Codename: content_chunk
 */
export function isBlock_ContentChunk(
  item: CoreContentType | undefined | null,
): item is Block_ContentChunk {
  return item?.system?.type === "content_chunk";
}
