import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_EmojiGuideline } from '../content-type-snippets/Block_EmojiGuideline';
import { type Fact } from './fact';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Hero unit
 * Id: 3436c1cd-fb6f-596d-a812-918cc5cd1e7f
 * Codename: hero_unit
 */
export type Block_HeroUnit = IContentItem<{
  /**
   * Background image (asset)
   * Required: false
   * Id: 688b3d35-b23c-5e2e-a183-57c0651e2161
   * Codename: background_image
   */
  backgroundImage: Elements.AssetsElement;

  /**
   * Fact (modular_content)
   * Required: true
   * Id: 170f10ce-8d2f-5594-aa09-e4d0cb1996e8
   * Codename: fact
   */
  fact: Elements.LinkedItemsElement<Fact>;

  /**
   * Target (text)
   * Required: false
   * Id: 8ca0ee74-9553-52f8-a103-236e5397ff11
   * Codename: target
   */
  target: Elements.TextElement;
}> &
  Block_EmojiGuideline;
