import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Card
 * Id: 10e9f753-bc03-4dc4-be56-b0805ecce699
 * Codename: card
 */
export type Card = IContentItem<{
  /**
   * Card image (asset)
   * Required: false
   * Id: 8c981733-f473-4ab7-8b6f-fab88d5fd64b
   * Codename: card_image
   */
  cardImage: Elements.AssetsElement;

  /**
   * Message (text)
   * Required: false
   * Id: 8515c2ca-1dd6-4cee-b5ce-710b77c7bb0d
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Redirect URL (text)
   * Required: false
   * Id: 701f593b-aca1-49d2-8810-1ac448ee16f0
   * Codename: redirect_url
   */
  redirectUrl: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 541b4fba-088a-4f59-9098-326eb7ff075c
   * Codename: title
   */
  title: Elements.TextElement;
}>;
