import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Footer
 * Id: 37153df0-4910-40fa-994f-f16e697aaf92
 * Codename: component___footer
 */
export type Footer = IContentItem<{}>;
