import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Component_EmojiGuideline } from '../content-type-snippets/Component_EmojiGuideline';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧩 Callout
 * Id: 7d0c0ae4-72e7-4678-ab62-01885ae8cd35
 * Codename: callout
 */
export type Component_Callout = IContentItem<{
  /**
   * Content (rich_text)
   * Required: true
   * Id: 76a0b381-b3a5-445d-8337-77c90297d7a2
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Type (multiple_choice)
   * Required: true
   * Id: b1a8da0e-2b24-44a0-826f-7029d2f59a1e
   * Codename: type
   */
  type: Elements.MultipleChoiceElement;
}> &
  Component_EmojiGuideline;
