
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * 🧩 Callout
 *
 * Id: 72c5b04f-e316-5912-baf2-8ccd2f0ad7a2
 * Codename: callout
 */
export type Component_Callout = CoreContentType<
  {
    /**
     * Type
     *
     * Type: multiple_choice
     * Required: true
     * Codename: type
     * Id: 44dd9032-c950-53b8-91bd-c6c586233311
     * Guidelines: Selecting a type affects the visual style of the callout to make its purpose instantly clear to the reader.
     */
    readonly type: Elements.MultipleChoiceElement<
      "warning" | "info" | "lightbulb"
    >;
    /**
     * Content
     *
     * Type: rich_text
     * Required: true
     * Codename: content
     * Id: 15a9fc79-e85f-5bb1-8e81-d0362cd93b93
     */
    readonly content: Elements.RichTextElement<CoreContentType>;
  },
  "callout"
>;

/**
 * Type representing all available element codenames for 🧩 Callout
 */
export type Component_CalloutElementCodenames = "type" | "content";

/**
 * Type guard for 🧩 Callout
 *
 * Id: 72c5b04f-e316-5912-baf2-8ccd2f0ad7a2
 * Codename: callout
 */
export function isComponent_Callout(
  item: CoreContentType | undefined | null,
): item is Component_Callout {
  return item?.system?.type === "callout";
}
