import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Solution
 * Id: 8cf1f294-22da-4ce9-8b9e-57e09d03c4d6
 * Codename: component___solution
 */
export type Solution = IContentItem<{
  /**
   * Background image (asset)
   * Required: false
   * Id: 98e2f96d-556b-4c01-afa8-b613d3dc3bbc
   * Codename: background_image
   */
  backgroundImage: Elements.AssetsElement;

  /**
   * Overview (rich_text)
   * Required: false
   * Id: 06bb2885-9c53-40b0-8429-c1f3b2ebb956
   * Codename: overview
   */
  overview: Elements.RichTextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 3fbe76f7-aef4-4336-8100-24f428a29ef8
   * Codename: title
   */
  title: Elements.TextElement;
}>;
