import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * CTA Button
 * Id: bbbce5ce-5a0c-45fe-8e32-bb6eb635510e
 * Codename: cta_button
 */
export type CTAButton = IContentItem<{
  /**
   * Button text (text)
   * Required: true
   * Id: 02379144-f60e-4877-9d2b-eb4bf1bc394a
   * Codename: button_text
   */
  buttonText: Elements.TextElement;

  /**
   * Target URL (text)
   * Required: true
   * Id: b57d180f-27af-41c5-a2ca-3cfcf4b2401f
   * Codename: target_url
   */
  targetUrl: Elements.TextElement;
}>;
