import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Fact
 * Id: df18210c-bacd-5980-81a7-b35c2a66d81f
 * Codename: fact
 */
export type Fact = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: 8c8946ce-e683-5df1-b029-967a3e43e056
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Message (text)
   * Required: false
   * Id: db8a7f6b-afd5-5170-bd6f-e450a96c8053
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: 75c5ed43-3eb7-5902-bf8b-4ddf8f830c8b
   * Codename: title
   */
  title: Elements.TextElement;
}>;
