import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Fact
 * Id: 10e9f753-bc03-4dc4-be56-b0805ecce699
 * Codename: fact
 */
export type Fact = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: 8c981733-f473-4ab7-8b6f-fab88d5fd64b
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Message (text)
   * Required: false
   * Id: 8515c2ca-1dd6-4cee-b5ce-710b77c7bb0d
   * Codename: message
   */
  message: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: 541b4fba-088a-4f59-9098-326eb7ff075c
   * Codename: title
   */
  title: Elements.TextElement;
}>;
