import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type FactType } from '../taxonomies/factType';
import { type Person } from './person';
import { type Reference } from '../content-type-snippets/reference';
import { type TitleMessage } from '../content-type-snippets/titleMessage';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Fact
 * Id: df18210c-bacd-5980-81a7-b35c2a66d81f
 * Codename: fact
 */
export type Fact = IContentItem<{
  /**
   * Author (modular_content)
   * Required: false
   * Id: db132f67-3b62-43d4-b091-bb74521d8aba
   * Codename: author
   */
  author: Elements.LinkedItemsElement<Person>;

  /**
   * Image (asset)
   * Required: false
   * Id: 8c8946ce-e683-5df1-b029-967a3e43e056
   * Codename: image
   */
  image: Elements.AssetsElement;

  /**
   * Fact type (taxonomy)
   * Required: false
   * Id: fcca0c9f-d619-48f4-835e-e50697724c5a
   * Codename: type
   *
   * Fact type serves only the purpose of inventory sorting. It does not affect visual representation in any way.
   */
  type: Elements.TaxonomyElement<FactType>;
}> &
  Reference &
  TitleMessage;
