import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Footer
 * Id: bff5f85d-c5b2-4fc3-9716-0436f91c2f61
 * Codename: footer
 */
export type Footer = IContentItem<{
  /**
   * Copyright notice (text)
   * Required: false
   * Id: c0cb527c-4743-4d08-b62a-5e02f197f2b3
   * Codename: copyright_notice
   */
  copyrightNotice: Elements.TextElement;
}>;
