import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CTAButton } from './cTAButton';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Hero unit
 * Id: 76f5b7c0-3d2d-40d9-a5a9-3e4d8ec71a54
 * Codename: component___hero_unit
 */
export type HeroUnit = IContentItem<{
  /**
   * Background image (asset)
   * Required: false
   * Id: f00f8f79-3a3b-4098-8143-c52f0804f27b
   * Codename: background_image
   */
  backgroundImage: Elements.AssetsElement;

  /**
   * Call to action (modular_content)
   * Required: false
   * Id: 0495dc8d-5ce8-47fc-ac6b-9fac99bcdbfa
   * Codename: call_to_action
   */
  callToAction: Elements.LinkedItemsElement<CTAButton>;

  /**
   * Subtitle (text)
   * Required: false
   * Id: a63b8dfd-3f13-43b7-9a63-02bf070c3cb0
   * Codename: subtitle
   */
  subtitle: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: 250e0af2-9305-47b8-acdb-9b65c70cbc06
   * Codename: title
   */
  title: Elements.TextElement;
}>;
