import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Page } from './page';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Homepage
 * Id: 57c5c255-acc4-474b-9f1e-9cf31e04ebd4
 * Codename: homepage
 */
export type Homepage = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 3244f976-db85-46f7-9b85-0c6162f03bfb
   * Codename: content
   */
  content: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: 85c6dfae-3495-4796-a688-4ce17168cc16
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<Page>;

  /**
   * Title (text)
   * Required: false
   * Id: 736ac36a-2c03-4590-befb-cd4f8c3a8a52
   * Codename: title
   */
  title: Elements.TextElement;
}>;
