import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Hosted video
 * Id: 269202ad-1d9d-47fd-b3e8-bdb05b3e3cf0
 * Codename: hosted_video
 */
export type HostedVideo = IContentItem<{
  /**
   * Video host (multiple_choice)
   * Required: true
   * Id: 87924912-4861-aa84-176a-1eae7b22529b
   * Codename: video_host
   */
  video_host: Elements.MultipleChoiceElement;

  /**
   * Video ID (text)
   * Required: true
   * Id: 116a2441-6441-7124-c85b-46a4fef5dcb9
   * Codename: video_id
   */
  video_id: Elements.TextElement;
}>;
