import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ImagingTechnology } from '../taxonomies/imagingTechnology';
import { type ProductBase } from '../content-type-snippets/productBase';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Imaging solution
 * Id: 6bf0eff1-fe6a-4180-8d2d-5e020f54db18
 * Codename: imaging_solution
 */
export type ImagingSolution = IContentItem<{
  /**
   * Imaging technology (taxonomy)
   * Required: true
   * Id: 4697ff5c-393e-4ff3-ae09-ebcee4d2eb2b
   * Codename: imaging_technology
   */
  imagingTechnology: Elements.TaxonomyElement<ImagingTechnology>;

  /**
   * Showcase (rich_text)
   * Required: false
   * Id: eca7b868-5f7e-4bab-a744-88c299ff5992
   * Codename: showcase
   */
  showcase: Elements.RichTextElement;
}> &
  ProductBase;
