
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type {
  LP_WebsiteRoot,
  Article,
  Product,
  Solution,
  Block_ContentChunk,
  Block_VisualContainer,
} from "./index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";

/**
 * 💡 Page
 *
 * Id: c99c1b81-dc7a-4926-869c-fbdf543f83fa
 * Codename: page
 */
export type LP_Page = CoreContentType<
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: e0b23157-f172-4a27-a47c-aa81095edb63
     */
    readonly title: Elements.TextElement;
    /**
     * Slug
     *
     * Type: url_slug
     * Required: false
     * Codename: slug
     * Id: 9f99dba7-76b8-47cb-a3a0-c5a7b87dbfc9
     * Guidelines: Make sure each page has a unique slug.
     */
    readonly slug: Elements.UrlSlugElement;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: a4f188c5-30c0-41aa-b238-b2777a6bb031
     * Guidelines: Page of a website for the website tree in live preview.
     */
    readonly subpages: Elements.LinkedItemsElement<
      LP_Page | LP_WebsiteRoot | Article | Product | Solution
    >;
    /**
     * Content
     *
     * Type: modular_content
     * Required: false
     * Codename: content
     * Id: 52e19e9e-ea63-4f8e-96e9-13c05a4e7429
     * Guidelines: Populate with 🧱 type items to define the landing page structure and design.
     */
    readonly content: Elements.LinkedItemsElement<
      Block_ContentChunk | Block_VisualContainer
    >;
  } & Metadata,
  "page"
>;

/**
 * Type representing all available element codenames for 💡 Page
 */
export type LP_PageElementCodenames =
  | "title"
  | "slug"
  | "subpages"
  | "content"
  | "metadata__title"
  | "metadata__description"
  | "metadata__keywords";

/**
 * Type guard for 💡 Page
 *
 * Id: c99c1b81-dc7a-4926-869c-fbdf543f83fa
 * Codename: page
 */
export function isLP_Page(
  item: CoreContentType | undefined | null,
): item is LP_Page {
  return item?.system?.type === "page";
}
