import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Milestone
 * Id: 59d408cc-299b-48d2-972b-22028e095963
 * Codename: milestone
 */
export type Milestone = IContentItem<{
  /**
   * Achievement (text)
   * Required: true
   * Id: f49769f4-7688-4fee-94e4-16174c03e049
   * Codename: achievement
   */
  achievement: Elements.TextElement;

  /**
   * Subject (text)
   * Required: true
   * Id: 7b04ac84-cdd9-4e30-b4f6-93ace70f4116
   * Codename: subject
   */
  subject: Elements.TextElement;
}>;
