import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Reference } from '../content-type-snippets/reference';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧭 Navigation item
 * Id: 08ad03e2-c164-56e7-9903-52f615e8ec82
 * Codename: navigation_item
 */
export type Nav_NavigationItem = IContentItem<{
  /**
   * Subitems (modular_content)
   * Required: false
   * Id: 2a2104ce-cb8d-5d6b-a90f-a78183efc478
   * Codename: subitems
   */
  subitems: Elements.LinkedItemsElement<Nav_NavigationItem>;
}> &
  Reference;
