
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Reference } from "../content-type-snippets/index.ts";

/**
 * 🧭 Navigation item
 *
 * Id: fc4d093f-9e1a-5c1a-a47c-21acf156dadf
 * Codename: navigation_item
 */
export type Nav_NavigationItem = CoreContentType<
  {
    /**
     * Subitems
     *
     * Type: modular_content
     * Required: false
     * Codename: subitems
     * Id: 673d7bea-bd01-5bc2-bbd2-e51abc5f24bb
     * Guidelines: Fill with further Navigation items to create a hierarchical menu.
     */
    readonly subitems: Elements.LinkedItemsElement<Nav_NavigationItem>;
  } & Reference,
  "navigation_item"
>;

/**
 * Type representing all available element codenames for 🧭 Navigation item
 */
export type Nav_NavigationItemElementCodenames =
  | "reference__label"
  | "reference__caption"
  | "reference__external_uri"
  | "reference__content__item_link"
  | "subitems";

/**
 * Type guard for 🧭 Navigation item
 *
 * Id: fc4d093f-9e1a-5c1a-a47c-21acf156dadf
 * Codename: navigation_item
 */
export function isNav_NavigationItem(
  item: CoreContentType | undefined | null,
): item is Nav_NavigationItem {
  return item?.system?.type === "navigation_item";
}
