import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Page
 * Id: 68bb8b01-1849-4570-9d08-7731f22c07b1
 * Codename: page
 */
export type Page = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 04032a7c-36a3-49b7-9d0f-cedad1f1679a
   * Codename: content
   */
  content: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Show in navigation (multiple_choice)
   * Required: false
   * Id: f70391e3-4d65-4fe7-8b85-c16580720ef5
   * Codename: show_in_navigation
   */
  show_in_navigation: Elements.MultipleChoiceElement;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: d854cf06-fde5-4dda-ba72-ac926452f9d9
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Title (text)
   * Required: false
   * Id: 7f40fdb1-f88b-47ed-bb1a-e640c2cd7cc1
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: false
   * Id: a0bd0f8e-f4ca-4792-84fe-ee947dffa214
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}>;
