import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Page
 * Id: af9ea390-7650-44f8-80e2-15d151cf67c9
 * Codename: page
 */
export type Page = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 0a60453b-1048-4d5e-b1ff-2f31b5027cca
   * Codename: content
   */
  content: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Show in navigation (multiple_choice)
   * Required: false
   * Id: 96ee042a-9d21-499b-8cfe-0069270f062c
   * Codename: show_in_navigation
   */
  showInNavigation: Elements.MultipleChoiceElement;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: 5ab7ce82-dc6d-49e6-abef-2fe24e6d8fa3
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<IContentItem>;

  /**
   * Title (text)
   * Required: false
   * Id: f0de57ce-52e4-4f77-9756-e1719d740b37
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: false
   * Id: b2850e82-078c-4836-828b-22e8d9b2c103
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}>;
