import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Person
 * Id: 3b8aea57-afdc-55b4-b7aa-30991e2515f8
 * Codename: person
 */
export type Person = IContentItem<{
    /**
     * Bio (rich_text)
     * Required: false
     * Id: 4341b423-f053-523f-bd0f-b63b6c786532
     * Codename: bio
     *
     * Write a biography that highlights the person's background and achievements. Don't forget to include relevant professional and educational information.
     */
    bio: Elements.RichTextElement;

    /**
     * First Name (text)
     * Required: true
     * Id: 412e6d34-62aa-524a-b97f-a23b2cf3e252
     * Codename: first_name
     */
    firstName: Elements.TextElement;

    /**
     * Last Name (text)
     * Required: true
     * Id: 3b153753-6cd6-58e8-99ae-e60020ffd890
     * Codename: last_name
     */
    lastName: Elements.TextElement;

    /**
     * Occupation (text)
     * Required: false
     * Id: d73579bd-b03a-59e0-8464-63939e0cb6c7
     * Codename: occupation
     *
     * Include relevant details about their job title or area of expertise.
     */
    occupation: Elements.TextElement;

    /**
     * Photograph (asset)
     * Required: false
     * Id: 514655d3-a35d-5c58-8807-b62108651728
     * Codename: photograph
     *
     * Use a clear, professional and high quality image.
     */
    photograph: Elements.AssetsElement;
}>;
