import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ProductCategory } from '../taxonomies/productCategory';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Product
 * Id: 28f3a148-bcdd-5a1a-b821-d54b2a94dabd
 * Codename: product
 */
export type Product = IContentItem<{
  /**
   * Description (text)
   * Required: false
   * Id: 283ff3b9-c4c5-511b-bb4b-50cf94b827bc
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Price (number)
   * Required: true
   * Id: 07b0eeae-1a51-5414-a6f9-0ddbb2e8e21a
   * Codename: price
   *
   * Price in Euros. ⚠️ Price element is here just for an illustration and should no be in production projects.
   */
  price: Elements.NumberElement;

  /**
   * Product category (taxonomy)
   * Required: true
   * Id: 5dac4e43-bea4-5373-b628-4006485b87a7
   * Codename: product_category
   */
  productCategory: Elements.TaxonomyElement<ProductCategory>;

  /**
   * Product image (asset)
   * Required: false
   * Id: 502b68a2-2d68-512a-b1f0-460c8bc38fe6
   * Codename: product_image
   *
   * Use images with no background if possible.
   */
  productImage: Elements.AssetsElement;

  /**
   * Slug (url_slug)
   * Required: false
   * Id: cb72527a-b7c5-5591-9a80-8415a799d4a6
   * Codename: slug
   */
  slug: Elements.UrlSlugElement;

  /**
   * Title (text)
   * Required: true
   * Id: 599d56c3-0840-5967-a869-1d41419775a4
   * Codename: title
   */
  title: Elements.TextElement;
}> &
  SEOMetadata;
