
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { Component_Callout, Fact, Action } from "./index.ts";
import type { CoreContentType } from "../system/index.ts";
import type { ImagingTechnology } from "../taxonomies/index.ts";
import type { ProductBase, Metadata } from "../content-type-snippets/index.ts";

/**
 * Solution
 *
 * Id: f750641e-b3aa-5e4a-9e21-c8871904894d
 * Codename: solution
 */
export type Solution = CoreContentType<
  {
    /**
     * Imaging technology
     *
     * Type: taxonomy
     * Required: true
     * Codename: imaging_technology
     * Id: 35fc766e-4d5d-58f1-a46f-3ea552eb388d
     * Guidelines: Select the type of imaging technology the solution employs.
     */
    readonly imaging_technology: Elements.TaxonomyElement<
      ImagingTechnology,
      "imaging_technology"
    >;
    /**
     * Showcase
     *
     * Type: rich_text
     * Required: false
     * Codename: showcase
     * Id: 42b24153-7274-550d-8fc1-5f5daea12e89
     * Guidelines: Detailed description of the solution and its benefits. Use Fact items to extend the showcase with captioned cards and a call-to-action.
     */
    readonly showcase: Elements.RichTextElement<
      Component_Callout | Fact | Action
    >;
    /**
     * Slug
     *
     * Type: url_slug
     * Required: false
     * Codename: slug
     * Id: 0e2c3f0c-9958-53e9-91e4-d6344e08e845
     * Guidelines: ⚠ Make sure each solution has a unique slug.
     */
    readonly slug: Elements.UrlSlugElement;
  } & Metadata &
    ProductBase,
  "solution"
>;

/**
 * Type representing all available element codenames for Solution
 */
export type SolutionElementCodenames =
  | "product_base__name"
  | "product_base__description"
  | "product_base__main_image"
  | "imaging_technology"
  | "showcase"
  | "slug"
  | "metadata__title"
  | "metadata__description"
  | "metadata__keywords";

/**
 * Type guard for Solution
 *
 * Id: f750641e-b3aa-5e4a-9e21-c8871904894d
 * Codename: solution
 */
export function isSolution(
  item: CoreContentType | undefined | null,
): item is Solution {
  return item?.system?.type === "solution";
}
