import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Solution set
 * Id: 1a1d2ce6-4a23-4428-acac-78205e9d72b5
 * Codename: solution_set
 */
export type SolutionSet = IContentItem<{
  /**
   * Solutions (modular_content)
   * Required: false
   * Id: 90719e11-0830-477c-991a-93ac31e1cc5b
   * Codename: solutions
   */
  solutions: Elements.LinkedItemsElement<IContentItem>;
}>;
