import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ProductBase } from '../content-type-snippets/productBase';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';
import { type SurgicalProductsCategory } from '../taxonomies/surgicalProductsCategory';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Surgical product
 * Id: 28f3a148-bcdd-5a1a-b821-d54b2a94dabd
 * Codename: surgical_product
 */
export type SurgicalProduct = IContentItem<{
  /**
   * Price (number)
   * Required: true
   * Id: 07b0eeae-1a51-5414-a6f9-0ddbb2e8e21a
   * Codename: price
   *
   * Price in Euros. ⚠️ Price element is here just for an illustration and should no be in production projects.
   */
  price: Elements.NumberElement;

  /**
   * Slug (url_slug)
   * Required: false
   * Id: cb72527a-b7c5-5591-9a80-8415a799d4a6
   * Codename: slug
   */
  slug: Elements.UrlSlugElement;

  /**
   * Surgical products category (taxonomy)
   * Required: true
   * Id: 6662b699-5be8-5056-a7f5-f0f75c5bace6
   * Codename: surgical_products_category
   */
  surgicalProductsCategory: Elements.TaxonomyElement<SurgicalProductsCategory>;
}> &
  ProductBase &
  SEOMetadata;
