import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Templated page
 * Id: 626ffac7-398f-407d-bbc2-56662331b530
 * Codename: templated_page
 */
export type TemplatedPage = IContentItem<{
  /**
   * Content (rich_text)
   * Required: false
   * Id: 445464b8-d1e7-4ce4-a360-801133113e2b
   * Codename: content
   */
  content: Elements.RichTextElement;

  /**
   * Publish date (date_time)
   * Required: false
   * Id: b4f07b7f-15ca-47e9-ab35-e2670394766e
   * Codename: publish_date
   */
  publishDate: Elements.DateTimeElement;

  /**
   * Title (text)
   * Required: false
   * Id: 3bf33c30-f2aa-43f2-8932-8cbb7292bd74
   * Codename: title
   */
  title: Elements.TextElement;
}>;
