import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './person';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Testimonial
 * Id: e3abca52-cc79-5b7d-821d-83f873e0a7ba
 * Codename: testimonial
 */
export type Testimonial = IContentItem<{
  /**
   * Author (modular_content)
   * Required: true
   * Id: b2760eb7-dd96-57dd-a6c4-25d01a756947
   * Codename: author
   */
  author: Elements.LinkedItemsElement<Person>;

  /**
   * Quote (text)
   * Required: true
   * Id: 955350b6-558a-5dcf-90c1-06d946fb90a0
   * Codename: quote
   */
  quote: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: e2b74907-fbc1-5fee-bb25-ef726b232b5e
   * Codename: title
   */
  title: Elements.TextElement;
}>;
