import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Testimonial
 * Id: 05cc2616-b52e-4746-a5fe-9dfb04c80907
 * Codename: testimonial
 */
export type Testimonial = IContentItem<{
  /**
   * Image (asset)
   * Required: false
   * Id: 2000aedc-4a17-4ff9-8978-f40aa5e8fa32
   * Codename: image
   */
  image: Elements.AssetsElement;
}>;
