import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Person } from './person';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Testimonial
 * Id: 05cc2616-b52e-4746-a5fe-9dfb04c80907
 * Codename: testimonial
 */
export type Testimonial = IContentItem<{
  /**
   * Author (modular_content)
   * Required: false
   * Id: 6811e346-dc62-48e5-b138-a63cb7b34c99
   * Codename: author
   */
  author: Elements.LinkedItemsElement<Person>;

  /**
   * Quote (text)
   * Required: false
   * Id: 1361ee48-656f-4f72-9c89-b9e8d3244085
   * Codename: quote
   */
  quote: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 08a335a9-fa58-455c-928c-df57e7402af5
   * Codename: title
   */
  title: Elements.TextElement;
}>;
