import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * UMLP component – Resource listing
 * Id: b6f5902d-8a00-494d-97dc-3bf99e3bf801
 * Codename: umlp_component___resource_listing
 */
export type UMLPComponent_ResourceListing = IContentItem<{}>;
