import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type UMLPComponent_CallToAction } from './UMLPComponent_CallToAction';
import { type UMLPComponent_HeroUnit } from './UMLPComponent_HeroUnit';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * UMLP component – Carousel
 * Id: f1e220f9-76af-4c78-8137-e2bfa026e320
 * Codename: carousel
 */
export type UMLPComponent_Carousel = IContentItem<{
  /**
   * Elements (modular_content)
   * Required: true
   * Id: fb6b765a-1d09-4d98-81db-66bc3a63c487
   * Codename: hero_units
   */
  heroUnits: Elements.LinkedItemsElement<
    UMLPComponent_HeroUnit | UMLPComponent_CallToAction
  >;
}>;
