import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
<<<<<<<< HEAD:models/content-types/Block_Grid.ts
import { type Milestone } from './milestone';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Grid
 * Id: 6f83adaa-788a-4778-8ed6-b64d73d54cff
 * Codename: grid
 */
export type Block_Grid = IContentItem<{
  /**
   * Grid items (modular_content)
========
import { Milestone } from './milestone';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * UMLP component – Milestones
 * Id: 6f83adaa-788a-4778-8ed6-b64d73d54cff
 * Codename: umlp_component___milestones
 */
export type UMLPComponent_Milestones = IContentItem<{
  /**
   * Milestones (modular_content)
>>>>>>>> 6147910 (make responsive, add smartlink, regenerate models):models/content-types/UMLPComponent_Milestones.ts
   * Required: false
   * Id: 43fad747-0fac-4559-a0e4-9b1576eff9e7
   * Codename: grid_items
   */
<<<<<<<< HEAD:models/content-types/Block_Grid.ts
  gridItems: Elements.LinkedItemsElement<Milestone>;
========
  achievements: Elements.LinkedItemsElement<Milestone>;
>>>>>>>> 6147910 (make responsive, add smartlink, regenerate models):models/content-types/UMLPComponent_Milestones.ts
}>;
