import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { Milestone } from './milestone';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * UMLP component – Milestones
 * Id: 6f83adaa-788a-4778-8ed6-b64d73d54cff
 * Codename: umlp_component___milestones
 */
export type UMLPComponent_Milestones = IContentItem<{
  /**
   * Milestones (modular_content)
   * Required: false
   * Id: 43fad747-0fac-4559-a0e4-9b1576eff9e7
   * Codename: achievements
   */
  achievements: Elements.LinkedItemsElement<Milestone>;
}>;
