import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
<<<<<<<< HEAD:models/content-types/Block_ContentChunk.ts
 * 🧱 Content chunk
========
 * UMLP component – Rich text content
>>>>>>>> fd2a16b93248bbdfd6c91e460c40d25f31157f28:models/content-types/UMLPComponent_RichTextContent.ts
 * Id: 7d315973-6157-4b4b-b722-0674b16121bf
 * Codename: content_chunk
 */
<<<<<<<< HEAD:models/content-types/Block_ContentChunk.ts
export type Block_ContentChunk = IContentItem<{
========
export type UMLPComponent_RichTextContent = IContentItem<{
>>>>>>>> fd2a16b93248bbdfd6c91e460c40d25f31157f28:models/content-types/UMLPComponent_RichTextContent.ts
  /**
   * Content (rich_text)
   * Required: false
   * Id: f7e1a1d0-f3cb-42f8-b7b1-4005fae328d0
   * Codename: content
   */
  content: Elements.RichTextElement;
}>;
