import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * UMLP component – Achievements
 * Id: 6f83adaa-788a-4778-8ed6-b64d73d54cff
 * Codename: umlp_component___achievements
 */
export type UMLPComponent_Achievements = IContentItem<{
  /**
   * Achievements (modular_content)
   * Required: false
   * Id: 43fad747-0fac-4559-a0e4-9b1576eff9e7
   * Codename: achievements
   */
  achievements: Elements.LinkedItemsElement<IContentItem>;
}>;
