
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type {
  WSL_Page,
  Nav_NavigationItem,
  Block_VisualContainer,
  Block_ContentChunk,
} from "./index.ts";

/**
 * 💡 Website root
 *
 * Id: bc0ca9d3-82be-439d-8488-3f6104d58125
 * Codename: website_root
 */
export type WSL_WebsiteRoot = CoreContentType<
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: 54e73153-a0df-4fd4-84c0-c69300767f60
     */
    readonly title: Elements.TextElement;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: fa27125f-c274-4ffe-bf4e-fef14bf47deb
     * Guidelines: Page of a website for the website tree in live preview.
     */
    readonly subpages: Elements.LinkedItemsElement<WSL_Page | WSL_WebsiteRoot>;
    /**
     * Navigation
     *
     * Type: modular_content
     * Required: true
     * Codename: navigation
     * Id: 49a9000d-8d82-5527-baca-d3fb97bebea0
     * Guidelines: Provide a valid Navigation item to define main website menu. Recursive nature of Navigation item type allows you to create a hierarchical mega menu. Two levels of nesting are supported by default.
     */
    readonly navigation: Elements.LinkedItemsElement<Nav_NavigationItem>;
    /**
     * Content
     *
     * Type: modular_content
     * Required: false
     * Codename: content
     * Id: 39ffd885-9768-48b9-88d9-2a4035edf1ed
     * Guidelines: Populate with 🧱 type items to define the landing page structure and design.
     */
    readonly content: Elements.LinkedItemsElement<
      Block_VisualContainer | Block_ContentChunk
    >;
  } & Metadata,
  "website_root"
>;

/**
 * Type representing all available element codenames for 💡 Website root
 */
export type WSL_WebsiteRootElementCodenames =
  | "title"
  | "subpages"
  | "navigation"
  | "content"
  | "metadata__title"
  | "metadata__description"
  | "metadata__keywords";

/**
 * Type guard for 💡 Website root
 *
 * Id: bc0ca9d3-82be-439d-8488-3f6104d58125
 * Codename: website_root
 */
export function isWSL_WebsiteRoot(
  item: CoreContentType | undefined | null,
): item is WSL_WebsiteRoot {
  return item?.system?.type === "website_root";
}
