import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_ContentChunk } from './Block_ContentChunk';
import { type Block_HeroUnit } from './Block_HeroUnit';
import { type Block_VisualContainer } from './Block_VisualContainer';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';
import { type Testimonial } from './testimonial';
import { type WSL_EmojiGuideline } from '../content-type-snippets/WSL_EmojiGuideline';
import { type WSL_WebSpotlightRoot } from './WSL_WebSpotlightRoot';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Page
 * Id: 0cb81f69-3f4b-46a1-8ce2-0aada4cdc358
 * Codename: page
 */
export type WSL_Page = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 27bc37be-796c-4219-a85d-cd61fc2e4f43
   * Codename: content
   */
  content: Elements.LinkedItemsElement<
    Block_HeroUnit | Block_ContentChunk | Testimonial | Block_VisualContainer
  >;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: 7e159b22-7b95-4a9b-9e2a-a79d407edd76
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<WSL_Page | WSL_WebSpotlightRoot>;

  /**
   * Title (text)
   * Required: false
   * Id: c2808c7e-9f57-4d0b-815c-f535752ed1cd
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: false
   * Id: 434f911b-c645-46e1-a633-0c8a3b1e9207
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}> &
  WSL_EmojiGuideline &
  SEOMetadata;
