import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Article } from './article';
import { type Block_ContentChunk } from './Block_ContentChunk';
import { type Block_VisualContainer } from './Block_VisualContainer';
import { type Nav_NavigationItem } from './Nav_NavigationItem';
import { type Product } from './product';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';
import { type WSL_EmojiGuideline } from '../content-type-snippets/WSL_EmojiGuideline';
import { type WSL_Page } from './WSL_Page';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Web spotlight root
 * Id: b5157974-9062-4e13-a7ca-37938122e1d7
 * Codename: web_spotlight_root
 */
export type WSL_WebSpotlightRoot = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 9dc587ef-e659-4e91-ae60-f6e54202c567
   * Codename: content
   */
  content: Elements.LinkedItemsElement<
    Block_ContentChunk | Block_VisualContainer
  >;

  /**
   * Navigation (modular_content)
   * Required: true
   * Id: a1a6b4d4-2f47-5071-aa53-1d283d2dee3e
   * Codename: navigation
   */
  navigation: Elements.LinkedItemsElement<Nav_NavigationItem>;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: ee6b535e-ac3b-4998-953d-bbdacac72d94
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<
    WSL_Page | WSL_WebSpotlightRoot | Article | Product
  >;

  /**
   * Title (text)
   * Required: false
   * Id: e30455a4-7293-4736-bceb-9725d43889f1
   * Codename: title
   */
  title: Elements.TextElement;
}> &
  WSL_EmojiGuideline &
  SEOMetadata;
