import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_ContentChunk } from './Block_ContentChunk';
import { type Block_HeroUnit } from './Block_HeroUnit';
import { type Block_VisualContainer } from './Block_VisualContainer';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';
import { type Testimonial } from './testimonial';
import { type WSL_EmojiGuideline } from '../content-type-snippets/WSL_EmojiGuideline';
import { type WSL_WebSpotlightRoot } from './WSL_WebSpotlightRoot';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Page
 * Id: 9ebc770b-20ae-4234-b1fa-439d70739ddc
 * Codename: page
 */
export type WSL_Page = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 7ead0693-d408-4899-91ba-97242b9fdfba
   * Codename: content
   */
  content: Elements.LinkedItemsElement<
    Block_HeroUnit | Block_ContentChunk | Testimonial | Block_VisualContainer
  >;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: 43eadf14-84d9-4f73-b47b-144ccfc46e9e
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<WSL_Page | WSL_WebSpotlightRoot>;

  /**
   * Title (text)
   * Required: false
   * Id: 45619a1e-6583-4449-ac88-07d0a8bf943b
   * Codename: title
   */
  title: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: false
   * Id: 8353d934-4b68-4322-b34c-254c732a52ae
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}> &
  WSL_EmojiGuideline &
  SEOMetadata;
