import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Block_ContentChunk } from './Block_ContentChunk';
import { type Block_VisualContainer } from './Block_VisualContainer';
import { type Nav_NavigationItem } from './Nav_NavigationItem';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';
import { type WSL_EmojiGuideline } from '../content-type-snippets/WSL_EmojiGuideline';
import { type WSL_Page } from './WSL_Page';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Web spotlight root
 * Id: ab387b8f-ec50-4876-9ecb-d175aef67003
 * Codename: web_spotlight_root
 */
export type WSL_WebSpotlightRoot = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 9f9bf380-8fdf-48e0-9808-1e1fc067dc1d
   * Codename: content
   */
  content: Elements.LinkedItemsElement<
    Block_ContentChunk | Block_VisualContainer
  >;

  /**
   * Navigation (modular_content)
   * Required: true
   * Id: a1a6b4d4-2f47-5071-aa53-1d283d2dee3e
   * Codename: navigation
   */
  navigation: Elements.LinkedItemsElement<Nav_NavigationItem>;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: d94c4178-d6fe-442d-a205-ff1c52c22b35
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<WSL_Page | WSL_WebSpotlightRoot>;

  /**
   * Title (text)
   * Required: false
   * Id: 69bd8e1b-f164-48b8-8351-77eb98488de1
   * Codename: title
   */
  title: Elements.TextElement;
}> &
  WSL_EmojiGuideline &
  SEOMetadata;
