import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Article } from './article';
import { type Block_ContentChunk } from './Block_ContentChunk';
import { type Block_VisualContainer } from './Block_VisualContainer';
import { type Product } from './product';
import { type SEOMetadata } from '../content-type-snippets/SEOMetadata';
import { type WSL_EmojiGuideline } from '../content-type-snippets/WSL_EmojiGuideline';
import { type WSL_WebSpotlightRoot } from './WSL_WebSpotlightRoot';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Page
 * Id: 62d2fd7d-404a-4b48-8f48-fb7ae680a3dd
 * Codename: page
 */
export type WSL_Page = IContentItem<{
  /**
   * Content (modular_content)
   * Required: false
   * Id: 6b8c0806-31e5-4544-8972-8b3b486a7121
   * Codename: content
   */
  content: Elements.LinkedItemsElement<
    Block_ContentChunk | Block_VisualContainer
  >;

  /**
   * Slug (url_slug)
   * Required: false
   * Id: 7e33180c-94ed-4880-8b92-2de577810e1b
   * Codename: slug
   */
  slug: Elements.UrlSlugElement;

  /**
   * Subpages (subpages)
   * Required: false
   * Id: 61ba5c0b-b4db-40f4-aa9c-b67f2c20a9c1
   * Codename: subpages
   */
  subpages: Elements.LinkedItemsElement<
    WSL_Page | WSL_WebSpotlightRoot | Article | Product
  >;

  /**
   * Title (text)
   * Required: false
   * Id: bb93490c-13de-43c4-a9ab-ec0f93b7324d
   * Codename: title
   */
  title: Elements.TextElement;
}> &
  WSL_EmojiGuideline &
  SEOMetadata;
