
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

/**
 * Article type
 *
 * Codename: article_type
 * Id: 37f4ed63-efb5-54cb-8cc9-4fdf63223f1e
 */
export type ArticleType = "post" | "news";
