/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Article type (new)
 * Id: 22734591-ab75-4912-9940-45935ce36488
 * Codename: article_type_2273459
 */
export type ArticleTypeNew = 'news' | 'post';
