/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Article type
 * Id: 7328c36a-d608-41eb-b640-71f7ac9bcd27
 * Codename: article_type
 */
export type ArticleType =
  | 'case_study'
  | 'clinical_trial'
  | 'industry_news'
  | 'research';
