/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Fact type
 * Id: c71e8cf8-5c3e-48a6-849c-184146874a27
 * Codename: fact_type
 */
export type FactType = 'card' | 'hero_unit' | 'milestone' | 'testimonial';
