/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Fact type
 * Id: aa3a8989-f8da-4a6e-bd9a-aacd862ea19b
 * Codename: fact_type
 */
export type FactType = 'card' | 'hero_unit' | 'milestone' | 'testimonial';
