
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

/**
 * Fact type
 *
 * Codename: fact_type
 * Id: 60c8d377-24b2-54f0-886b-18aaa0f1095b
 */
export type FactType = "card" | "hero_unit" | "milestone" | "testimonial";
