
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

/**
 * Imaging technology
 *
 * Codename: imaging_technology
 * Id: 5cf829cd-e8fe-56c2-89be-369de0a0b8ff
 */
export type ImagingTechnology = "mri" | "pet" | "x_ray";
