/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Imaging technology
 * Id: 9b4ad3e0-fcc0-43f5-8b85-74286a260141
 * Codename: imaging_technology
 */
export type ImagingTechnology = 'mri' | 'pet' | 'x_ray';
