
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

/**
 * Product category
 *
 * Codename: product_category
 * Id: 502de9a1-3673-51e5-bf88-92e76c35cbee
 */
export type ProductCategory =
  | "cutting"
  | "hand_held"
  | "self_retaining"
  | "retracting"
  | "grasping";
