/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Product category (Old)
 * Id: 54634713-6a9f-5b20-a724-693b2372499e
 * Codename: product_category_old
 */
export type ProductCategoryOld =
  | 'clothing'
  | 'equipment'
  | 'other'
  | 'precision_instruments'
  | 'sanitary_clothing'
  | 'tools';
