/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Product category
 * Id: e70e602f-49c6-4980-a748-5a6263d366c5
 * Codename: product_category
 */
export type ProductCategory =
  | 'clothing'
  | 'equipment'
  | 'other'
  | 'precision_instruments'
  | 'sanitary_clothing'
  | 'tools';
