/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Surgical products category
 * Id: 70a6b135-42e7-56ae-a15a-dfa8119455f5
 * Codename: surgical_products_category
 */
export type SurgicalProductsCategory =
  | 'cutting'
  | 'grasping'
  | 'hand_held'
  | 'retracting'
  | 'self_retaining';
