/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Surgical product category
 * Id: f5b4664d-d982-4ce9-8f68-0b94670371da
 * Codename: surgical_product_category
 */
export type SurgicalProductCategory =
  | 'cutting'
  | 'grasping'
  | 'hand_held'
  | 'retracting'
  | 'self_retaining';
