
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Snippet } from "@kontent-ai/delivery-sdk";

/**
 * 🧱 Block guidelines
 *
 * Id: 0b86d622-6911-52d9-a8c0-a3638dd0243c
 * Codename: block_guidelines
 */
export type Block_BlockGuidelines = Snippet<
  Block_BlockGuidelinesElementCodenames,
  Record<string, never>
>;

/**
 * Type representing all available element codenames for 🧱 Block guidelines
 */
export type Block_BlockGuidelinesElementCodenames = never;
