import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * 🧱 Block guidelines
 * Id: f6739376-35b8-598f-8643-2f4f12992fe3
 * Codename: visual_component_guidelines
 */
export type Block_BlockGuidelines = IContentItem<{}>;
