import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Emoji guideline
 * Id: f6739376-35b8-598f-8643-2f4f12992fe3
 * Codename: _emoji_guideline
 */
export type Block_EmojiGuideline = IContentItem<{}>;
