import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧱 Emoji guideline
 * Id: 09485dd4-6af3-4483-8e3a-8ab6a83743ed
 * Codename: emoji_guideline
 */
export type Block_EmojiGuideline = IContentItem<{}>;
