
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Snippet } from "@kontent-ai/delivery-sdk";

/**
 * 🧩 Component guidelines
 *
 * Id: 40f2499f-6de6-5713-b1f9-2eb50d49d88c
 * Codename: component_guidelines
 */
export type Component_ComponentGuidelines = Snippet<
  Component_ComponentGuidelinesElementCodenames,
  Record<string, never>
>;

/**
 * Type representing all available element codenames for 🧩 Component guidelines
 */
export type Component_ComponentGuidelinesElementCodenames = never;
