import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧩 Emoji guideline
 * Id: 0de9f7c1-1ce0-591d-b93f-fe4859efd627
 * Codename: _emoji_guideline_0de9f7c
 */
export type Component_EmojiGuideline = IContentItem<{}>;
