import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * 🧩 Component guidelines
 * Id: 0de9f7c1-1ce0-591d-b93f-fe4859efd627
 * Codename: component_guidelines
 */
export type Component_ComponentGuidelines = IContentItem<{}>;
