import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 🧩 Emoji guideline
 * Id: 590e3d38-a5d6-46ab-a3a1-1cc47869c34a
 * Codename: _emoji_guideline
 */
export type Component_EmojiGuideline = IContentItem<{}>;
