
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Snippet } from "@kontent-ai/delivery-sdk";

/**
 * 💡 Live preview guidelines
 *
 * Id: b0299f53-78b4-5c20-bbf3-7cc9129cdb12
 * Codename: live_preview_guidelines
 */
export type LP_LivePreviewGuidelines = Snippet<
  LP_LivePreviewGuidelinesElementCodenames,
  Record<string, never>
>;

/**
 * Type representing all available element codenames for 💡 Live preview guidelines
 */
export type LP_LivePreviewGuidelinesElementCodenames = never;
