import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Metadata
 * Id: 3ad33660-1d2b-578b-8b3e-129f2a2e552f
 * Codename: metadata
 */
export type Metadata = IContentItem<{
    /**
     * Description (text)
     * Required: false
     * Id: 0ae36299-95cb-54d7-9be9-7d76ee6f4be0
     * Codename: metadata__description
     */
    metadataDescription: Elements.TextElement;

    /**
     * Keywords (text)
     * Required: false
     * Id: a0f7ffe0-5e94-532f-a86e-d77761eb35af
     * Codename: metadata__keywords
     */
    metadataKeywords: Elements.TextElement;

    /**
     * Title (text)
     * Required: false
     * Id: d278379c-9f60-58f8-92e0-0e665033dd95
     * Codename: metadata__title
     */
    metadataTitle: Elements.TextElement;
}>;
