
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";

/**
 * Product base
 *
 * Id: 93c26558-f7e5-57ea-802f-5f1f079ea7a9
 * Codename: product_base
 */
export type ProductBase = Snippet<
  ProductBaseElementCodenames,
  {
    /**
     * Name
     *
     * Type: text
     * Required: true
     * Codename: product_base__name
     * Id: 9647f1cc-3870-5b67-874b-d56fc2abd7ad
     * Guidelines: Include key product attributes, such as brand name or model.
     */
    readonly product_base__name: Elements.TextElement;
    /**
     * Description
     *
     * Type: text
     * Required: false
     * Codename: product_base__description
     * Id: 30f6b775-071e-5a5a-9394-8251d2081b0e
     */
    readonly product_base__description: Elements.TextElement;
    /**
     * Main image
     *
     * Type: asset
     * Required: false
     * Codename: product_base__main_image
     * Id: 333cb56d-09c7-58a9-b759-97a0931ce8e6
     */
    readonly product_base__main_image: Elements.AssetsElement;
  }
>;

/**
 * Type representing all available element codenames for Product base
 */
export type ProductBaseElementCodenames =
  | "product_base__name"
  | "product_base__description"
  | "product_base__main_image";
