
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements, Snippet } from "@kontent-ai/delivery-sdk";
import type {
  WSL_WebSpotlightRoot,
  WSL_Page,
  Article,
  Product,
  Solution,
} from "../content-types/index.ts";

/**
 * Reference
 *
 * Id: 6761a539-765f-5bff-a370-f2f4bff66eb4
 * Codename: reference
 */
export type Reference = Snippet<
  ReferenceElementCodenames,
  {
    /**
     * Label
     *
     * Type: text
     * Required: false
     * Codename: reference__label
     * Id: 15ee4053-00fd-5d5e-a2d7-4437079251ce
     */
    readonly reference__label: Elements.TextElement;
    /**
     * Caption
     *
     * Type: text
     * Required: false
     * Codename: reference__caption
     * Id: 75684270-5e43-5d21-b93a-700f85e50853
     */
    readonly reference__caption: Elements.TextElement;
    /**
     * External URI
     *
     * Type: text
     * Required: false
     * Codename: reference__external_uri
     * Id: 580e3f46-f033-50d4-9f34-4ed91384f4e4
     * Guidelines: Link to an external resource, has higher resolution priority than item link.
     */
    readonly reference__external_uri: Elements.TextElement;
    /**
     * Content item link
     *
     * Type: modular_content
     * Required: false
     * Codename: reference__content__item_link
     * Id: ed9d88d5-2375-57c3-9916-615eaae7d5da
     * Guidelines: Link to a supported content item, resolution can vary based on presentation layer.
     */
    readonly reference__content__item_link: Elements.LinkedItemsElement<
      WSL_WebSpotlightRoot | WSL_Page | Article | Product | Solution
    >;
  }
>;

/**
 * Type representing all available element codenames for Reference
 */
export type ReferenceElementCodenames =
  | "reference__label"
  | "reference__caption"
  | "reference__external_uri"
  | "reference__content__item_link";
