import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Article } from '../content-types/article';
import { type Product } from '../content-types/product';
import { type WSL_Page } from '../content-types/WSL_Page';
import { type WSL_WebSpotlightRoot } from '../content-types/WSL_WebSpotlightRoot';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Reference
 * Id: 510b73ca-4108-4235-bd42-e9d7c22ffaec
 * Codename: reference
 */
export type Reference = IContentItem<{
  /**
   * Caption (text)
   * Required: false
   * Id: 22581583-a2a6-4d72-a0bf-f0eb55e541eb
   * Codename: reference__caption
   */
  referenceCaption: Elements.TextElement;

  /**
   * Content item link (modular_content)
   * Required: false
   * Id: 4a90e2f3-517d-4092-9fdc-bbfb196ef250
   * Codename: reference__content_item_link
   *
   * Link to a supported content item, resolution can vary based on presentation layer.
   */
  referenceContentItemLink: Elements.LinkedItemsElement<
    WSL_WebSpotlightRoot | WSL_Page | Product | Article
  >;

  /**
   * External URI (text)
   * Required: false
   * Id: 6e1192e9-dd9e-4a04-bb51-445c771353c6
   * Codename: reference__external_uri
   *
   * Link to an external resource, has higher resolution priority than item link.
   */
  referenceExternalUri: Elements.TextElement;

  /**
   * Label (text)
   * Required: false
   * Id: af93c504-7db2-44cb-863a-59a0e9364e6e
   * Codename: reference__label
   */
  referenceLabel: Elements.TextElement;
}>;
