import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * SEO Metadata
 * Id: 22775c9b-d269-4b03-941f-8dc0ee6c00c0
 * Codename: seo_metadata
 */
export type SEOMetadata = IContentItem<{
  /**
   * Description (text)
   * Required: false
   * Id: 0848a00d-f935-4270-b9b5-ba0b22d7eaa2
   * Codename: seo_metadata__description
   */
  seoMetadataDescription: Elements.TextElement;

  /**
   * og:image (text)
   * Required: false
   * Id: 96973c48-0433-46e8-8efd-9e26418dc30a
   * Codename: seo_metadata__og_image
   */
  seoMetadataOgImage: Elements.TextElement;

  /**
   * og:type (text)
   * Required: false
   * Id: 0ddecb17-cca6-465d-8aa6-7f94945e054c
   * Codename: seo_metadata__og_type
   */
  seoMetadataOgType: Elements.TextElement;
}>;
