import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Title & message
 * Id: 70b793f6-7517-43f0-86f4-cacc44da73c3
 * Codename: title___message
 */
export type TitleMessage = IContentItem<{
  /**
   * Message (text)
   * Required: false
   * Id: 9f4ebd8f-1e71-4273-8348-777d6dbf197f
   * Codename: title___message__message
   */
  titleMessageMessage: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: 5cf411ef-3d13-484a-80c4-591d2c16d2c5
   * Codename: title___message__title
   */
  titleMessageTitle: Elements.TextElement;
}>;
