import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Title & Message
 * Id: fb2b5e89-48e9-4e58-8550-46e9a5706d89
 * Codename: title___message
 */
export type TitleMessage = IContentItem<{
  /**
   * Message (text)
   * Required: false
   * Id: f67acf88-b4e6-46af-afb1-213419dce742
   * Codename: title___message__message
   */
  titleMessageMessage: Elements.TextElement;

  /**
   * Title (text)
   * Required: false
   * Id: b03b13f3-b44a-425f-a51b-75e1390cfa7d
   * Codename: title___message__title
   */
  titleMessageTitle: Elements.TextElement;
}>;
