import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Emoji guideline
 * Id: c0e99be6-4a78-4f1b-954e-93793109c67e
 * Codename: _web_spotlight_root
 */
export type WSL_EmojiGuideline = IContentItem<{}>;
