import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Emoji guideline
 * Id: 90c26f3d-2866-5955-b65e-f52ad8a0a481
 * Codename: _emoji_guideline_90c26f3
 */
export type WSL_EmojiGuideline = IContentItem<{}>;
