import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * 💡 Spotlight guidelines
 * Id: 90c26f3d-2866-5955-b65e-f52ad8a0a481
 * Codename: spotlight_guidelines
 */
export type WSL_SpotlightGuidelines = IContentItem<{}>;
