
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-14'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Ficto Healthtech [QA Source project]
* Environment: Production 
* Id: b0255462-358c-007b-0be0-43ee125ce1f0
* 
* -------------------------------------------------------------------------------
**/

import type { Snippet } from "@kontent-ai/delivery-sdk";

/**
 * 💡 Spotlight guidelines
 *
 * Id: b0299f53-78b4-5c20-bbf3-7cc9129cdb12
 * Codename: spotlight_guidelines
 */
export type WSL_SpotlightGuidelines = Snippet<
  WSL_SpotlightGuidelinesElementCodenames,
  Record<string, never>
>;

/**
 * Type representing all available element codenames for 💡 Spotlight guidelines
 */
export type WSL_SpotlightGuidelinesElementCodenames = never;
