/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: New sample migrations (TMP) (Kontent)
 * Environment: App test
 * Project Id: 89962bec-344a-01fd-58aa-40c92b21f579
 */
export const assetFolders = {
  /**
   * Articles
   */
  articles: {
    id: '61dc2ee4-baf6-5068-b5b4-f3c0f9379464',
    name: 'Articles',
    externalId: 'articlesFolder-09c527ac-e9ef-41bd-9791-db403787e04a',
    folders: {},
  },

  /**
   * Guidelines
   */
  guidelines: {
    id: '73fb95ca-61ca-52b9-9fb2-b77651085c43',
    name: 'Guidelines',
    externalId: 'guidelinesFolder-bae9ec74-2b05-4c18-836a-d6d92da859b3',
    folders: {},
  },

  /**
   * Hero Images
   */
  heroImages: {
    id: '5b2a07cc-ba47-50cc-b2a1-5ca02cb5c201',
    name: 'Hero Images',
    externalId: 'heroImagesFolder-3b91643c-4f90-4ee6-a941-78ea192b07cb',
    folders: {},
  },

  /**
   * People
   */
  people: {
    id: '4322f8b1-594e-5925-80d3-1be109f38b45',
    name: 'People',
    externalId: 'peopleFolder-986836df-3df4-4129-b28a-43de29172c26',
    folders: {},
  },

  /**
   * Product images
   */
  productImages: {
    id: 'd6707ec8-be64-53db-8bab-f6ffb5fc08dd',
    name: 'Product images',
    externalId: 'productsFolder-ab01abd9-9673-41a1-a4d5-3a1ccccae295',
    folders: {},
  },
} as const;
