/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: HealthTech
 * Environment: New Production
 * Project Id: 0a12060e-20af-0124-a95d-871d26379561
 */
export const assetFolders = {
  /**
   * Authors
   */
  authors: {
    id: '08245518-a036-4b9a-b641-969f8fb43ab3',
    name: 'Authors',
    externalId: undefined,
    folders: {},
  },

  /**
   * Hero images
   */
  heroImages: {
    id: '002d1050-7e61-4268-8b62-fca9508071cf',
    name: 'Hero images',
    externalId: undefined,
    folders: {},
  },

  /**
   * Product images
   */
  productImages: {
    id: '9f1a4a41-e4da-45a1-b793-cb708f3b7db3',
    name: 'Product images',
    externalId: undefined,
    folders: {},
  },
} as const;
