/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: New sample project
 * Environment: Production
 * Project Id: 2cedc519-a547-01ba-dde7-b01e00b909a1
 */
export const assetFolders = {
  /**
   * Authors
   */
  authors: {
    id: '08245518-a036-4b9a-b641-969f8fb43ab3',
    name: 'Authors',
    externalId: undefined,
    folders: {},
  },

  /**
   * Hero images
   */
  heroImages: {
    id: '002d1050-7e61-4268-8b62-fca9508071cf',
    name: 'Hero images',
    externalId: undefined,
    folders: {},
  },
} as const;
