/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: New sample project
 * Environment: Production
 * Project Id: 2cedc519-a547-01ba-dde7-b01e00b909a1
 */
export const collections = {
  /**
   * Common
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Common',
  },

  /**
   * HealthTech
   */
  healthtech_medical: {
    codename: 'healthtech_medical',
    id: '63ff94b8-a191-4979-a897-a64bc46979d7',
    name: 'HealthTech',
  },

  /**
   * HealthTech Imaging
   */
  healthtech_imaging: {
    codename: 'healthtech_imaging',
    id: 'ac38396d-da5d-4f02-afb0-0f6e8d9f5d22',
    name: 'HealthTech Imaging',
  },

  /**
   * HealthTech Surgical
   */
  healthtech_surgical: {
    codename: 'healthtech_surgical',
    id: '29b05ad9-0308-45af-b1db-0871a8d0e696',
    name: 'HealthTech Surgical',
  },
} as const;
