/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: HealthTech
 * Environment: Development
 * Project Id: 0a12060e-20af-0124-a95d-871d26379561
 */
export const collections = {
  /**
   * Common
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Common',
  },

  /**
   * HealthTech
   */
  healthtech: {
    codename: 'healthtech',
    id: '4925dca2-e330-4f55-b647-9b2ec310e453',
    name: 'HealthTech',
  },

  /**
   * HealthTech Imaging
   */
  healthtech_imaging: {
    codename: 'healthtech_imaging',
    id: 'ac38396d-da5d-4f02-afb0-0f6e8d9f5d22',
    name: 'HealthTech Imaging',
  },

  /**
   * HealthTech Surgical
   */
  healthtech_surgical: {
    codename: 'healthtech_surgical',
    id: '29b05ad9-0308-45af-b1db-0871a8d0e696',
    name: 'HealthTech Surgical',
  },
} as const;
