/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Ficto Healthtech [QA Source project]
 * Environment: DanielP: Development
 * Project Id: 423ac17f-a20e-001f-3d73-6e446bf72c72
 */
export const collections = {
  /**
   * Common
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Common',
  },

  /**
   * Ficto Healthtech
   */
  ficto_healthtech: {
    codename: 'ficto_healthtech',
    id: '5eb3c621-9492-524e-a061-9ee80bbfc947',
    name: 'Ficto Healthtech',
  },

  /**
   * Ficto Imaging
   */
  ficto_healthtech_imaging: {
    codename: 'ficto_healthtech_imaging',
    id: '4fc9b159-8a85-581f-8803-e606528dbfdd',
    name: 'Ficto Imaging',
  },

  /**
   * Ficto Surgical
   */
  ficto_surgical: {
    codename: 'ficto_surgical',
    id: 'b77e2cf9-e408-4a60-9dc9-b50260c5ef21',
    name: 'Ficto Surgical',
  },
} as const;
