/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: HealthTech
 * Environment: New Production
 * Project Id: 0a12060e-20af-0124-a95d-871d26379561
 */
export const contentTypes = {
  /**
   * 💡 Page
   */
  page: {
    codename: 'page',
    id: 'af9ea390-7650-44f8-80e2-15d151cf67c9',
    externalId: undefined,
    name: '💡 Page',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: '0a60453b-1048-4d5e-b1ff-2f31b5027cca',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '5ab7ce82-dc6d-49e6-abef-2fe24e6d8fa3',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'f0de57ce-52e4-4f77-9756-e1719d740b37',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * URL (url_slug)
       */
      url: {
        codename: 'url',
        id: 'b2850e82-078c-4836-828b-22e8d9b2c103',
        externalId: undefined,
        name: 'URL',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 💡 Web spotlight root
   */
  web_spotlight_root: {
    codename: 'web_spotlight_root',
    id: '228de48c-ffb2-4b5e-862f-47e2c60e0c01',
    externalId: undefined,
    name: '💡 Web spotlight root',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: '94e31e00-81b8-4ab4-b17b-7d165ed3020e',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Navigation (modular_content)
       */
      navigation: {
        codename: 'navigation',
        id: 'a026a51c-fa29-4dfd-bf6b-cafe2f0ecb0f',
        externalId: undefined,
        name: 'Navigation',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '61be1529-49fc-43b6-ba33-962a360e4c9f',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '9a340e66-9416-455e-8763-848a330a4b2e',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧩 Callout
   */
  callout: {
    codename: 'callout',
    id: '7d0c0ae4-72e7-4678-ab62-01885ae8cd35',
    externalId: undefined,
    name: '🧩 Callout',
    elements: {
      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '76a0b381-b3a5-445d-8337-77c90297d7a2',
        externalId: undefined,
        name: 'Content',
        required: true,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Type (multiple_choice)
       */
      type: {
        codename: 'type',
        id: 'b1a8da0e-2b24-44a0-826f-7029d2f59a1e',
        externalId: undefined,
        name: 'Type',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Call to action
   */
  call_to_action: {
    codename: 'call_to_action',
    id: '11c3fbcd-2de0-4f56-96e5-f080bb9a28d1',
    externalId: undefined,
    name: '🧱 Call to action',
    elements: {
      /**
       * Action (modular_content)
       */
      action: {
        codename: 'action',
        id: '1d6a4e9b-29b3-4f62-a418-278bc71c3f9c',
        externalId: undefined,
        name: 'Action',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subtitle (text)
       */
      subtitle: {
        codename: 'subtitle',
        id: '1feb250b-c828-4b32-9196-d70d66b84bd9',
        externalId: undefined,
        name: 'Subtitle',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '2a1e51f1-3128-4321-8cf5-38e821712af0',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Carousel
   */
  carousel: {
    codename: 'carousel',
    id: 'f1e220f9-76af-4c78-8137-e2bfa026e320',
    externalId: undefined,
    name: '🧱 Carousel',
    elements: {
      /**
       * Elements (modular_content)
       */
      elements: {
        codename: 'elements',
        id: 'fb6b765a-1d09-4d98-81db-66bc3a63c487',
        externalId: undefined,
        name: 'Elements',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Content chunk
   */
  content_chunk: {
    codename: 'content_chunk',
    id: '7d315973-6157-4b4b-b722-0674b16121bf',
    externalId: undefined,
    name: '🧱 Content chunk',
    elements: {
      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: 'f7e1a1d0-f3cb-42f8-b7b1-4005fae328d0',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Grid
   */
  grid: {
    codename: 'grid',
    id: '6f83adaa-788a-4778-8ed6-b64d73d54cff',
    externalId: undefined,
    name: '🧱 Grid',
    elements: {
      /**
       * Grid items (modular_content)
       */
      grid_items: {
        codename: 'grid_items',
        id: '43fad747-0fac-4559-a0e4-9b1576eff9e7',
        externalId: undefined,
        name: 'Grid items',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Hero unit
   */
  hero_unit: {
    codename: 'hero_unit',
    id: '76f5b7c0-3d2d-40d9-a5a9-3e4d8ec71a54',
    externalId: undefined,
    name: '🧱 Hero unit',
    elements: {
      /**
       * Background image (asset)
       */
      background_image: {
        codename: 'background_image',
        id: 'f00f8f79-3a3b-4098-8143-c52f0804f27b',
        externalId: undefined,
        name: 'Background image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Subtitle (text)
       */
      subtitle: {
        codename: 'subtitle',
        id: 'a63b8dfd-3f13-43b7-9a63-02bf070c3cb0',
        externalId: undefined,
        name: 'Subtitle',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '250e0af2-9305-47b8-acdb-9b65c70cbc06',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Stack
   */
  stack: {
    codename: 'stack',
    id: 'e0ee220a-4d5d-4a9a-aa9c-6733433bf4a2',
    externalId: undefined,
    name: '🧱 Stack',
    elements: {
      /**
       * Message (text)
       */
      message: {
        codename: 'message',
        id: 'fd56aff1-e0f8-4611-ac59-3c14dfb647e9',
        externalId: undefined,
        name: 'Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Stack (modular_content)
       */
      stack: {
        codename: 'stack',
        id: '03baf56e-27a7-4f3a-be28-86f5deafc3f9',
        externalId: undefined,
        name: 'Stack',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '489177d9-8fab-4ad0-bc57-92c107b340b0',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Testimonial
   */
  testimonial: {
    codename: 'testimonial',
    id: '05cc2616-b52e-4746-a5fe-9dfb04c80907',
    externalId: undefined,
    name: '🧱 Testimonial',
    elements: {
      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: '6811e346-dc62-48e5-b138-a63cb7b34c99',
        externalId: undefined,
        name: 'Author',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Format (multiple_choice)
       *
       * Defines how the individual testimonial elements are organized.
       */
      format: {
        codename: 'format',
        id: '999d2af3-212d-4d5d-9348-5e14c3e9f957',
        externalId: undefined,
        name: 'Format',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Subtitle (text)
       */
      subtitle: {
        codename: 'subtitle',
        id: '1361ee48-656f-4f72-9c89-b9e8d3244085',
        externalId: undefined,
        name: 'Subtitle',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '08a335a9-fa58-455c-928c-df57e7402af5',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Article
   */
  article: {
    codename: 'article',
    id: 'e45f98c8-9175-4894-b5a7-7e996a4235e4',
    externalId: undefined,
    name: 'Article',
    elements: {
      /**
       * Abstract (text)
       */
      abstract: {
        codename: 'abstract',
        id: '227c0a71-1a5e-403f-9e49-8c5d7fa4f860',
        externalId: undefined,
        name: 'Abstract',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Article type (taxonomy)
       */
      article_type: {
        codename: 'article_type',
        id: '71c195b1-521c-49e3-85ed-e39b114b6673',
        externalId: undefined,
        name: 'Article type',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: 'cbc1433d-6449-4ce8-bdd6-215eb92362c5',
        externalId: undefined,
        name: 'Author',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '744d0b97-7fd9-48ed-832a-f153dcf75532',
        externalId: undefined,
        name: 'Content',
        required: true,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '0848a00d-f935-4270-b9b5-ba0b22d7eaa2',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Hero Image (asset)
       */
      hero_image: {
        codename: 'hero_image',
        id: '7735f75c-88d7-4f3a-a66b-c0d2338af4c8',
        externalId: undefined,
        name: 'Hero Image',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * og:image (text)
       */
      seo_metadata__og_image: {
        codename: 'seo_metadata__og_image',
        id: '96973c48-0433-46e8-8efd-9e26418dc30a',
        externalId: undefined,
        name: 'og:image',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * og:type (text)
       */
      seo_metadata__og_type: {
        codename: 'seo_metadata__og_type',
        id: '0ddecb17-cca6-465d-8aa6-7f94945e054c',
        externalId: undefined,
        name: 'og:type',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Publishing date (date_time)
       */
      publishing_date: {
        codename: 'publishing_date',
        id: 'ceb09050-d3e8-4e62-8f07-ea12d4b9e59d',
        externalId: undefined,
        name: 'Publishing date',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Slug (url_slug)
       */
      slug: {
        codename: 'slug',
        id: '1c06cbbc-914d-4305-a44a-67467d7c51a4',
        externalId: undefined,
        name: 'Slug',
        required: true,
        type: 'url_slug',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '390ac36a-028a-4bf6-bc1c-f3ab2f0f4e8f',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Author
   */
  author: {
    codename: 'author',
    id: '7f460e72-16d1-4403-b084-d01edcbcc578',
    externalId: undefined,
    name: 'Author',
    elements: {
      /**
       * Bio (rich_text)
       */
      bio: {
        codename: 'bio',
        id: 'a8786f1b-3e3c-42e1-92ae-9ef9cf53864c',
        externalId: undefined,
        name: 'Bio',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * First Name (text)
       */
      first_name: {
        codename: 'first_name',
        id: '0cfa6910-1b04-4489-a352-d15970f7357c',
        externalId: undefined,
        name: 'First Name',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Last Name (text)
       */
      last_name: {
        codename: 'last_name',
        id: '07994d54-d6a1-45e4-82cb-7094a29813b8',
        externalId: undefined,
        name: 'Last Name',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Occupation (text)
       */
      occupation: {
        codename: 'occupation',
        id: '135f68aa-c374-4a37-ac04-990f53061c9f',
        externalId: undefined,
        name: 'Occupation',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Photograph (asset)
       */
      photograph: {
        codename: 'photograph',
        id: 'b31f2ae2-7db3-494a-a871-edf79923a2a7',
        externalId: undefined,
        name: 'Photograph',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Footer
   */
  footer: {
    codename: 'footer',
    id: 'bff5f85d-c5b2-4fc3-9716-0436f91c2f61',
    externalId: undefined,
    name: 'Footer',
    elements: {
      /**
       * Copyright notice (text)
       */
      copyright_notice: {
        codename: 'copyright_notice',
        id: 'c0cb527c-4743-4d08-b62a-5e02f197f2b3',
        externalId: undefined,
        name: 'Copyright notice',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Generic action
   */
  generic_action: {
    codename: 'generic_action',
    id: '10e9f753-bc03-4dc4-be56-b0805ecce699',
    externalId: undefined,
    name: 'Generic action',
    elements: {
      /**
       * Image (asset)
       */
      card_image: {
        codename: 'card_image',
        id: '8c981733-f473-4ab7-8b6f-fab88d5fd64b',
        externalId: undefined,
        name: 'Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Message (text)
       */
      message: {
        codename: 'message',
        id: '8515c2ca-1dd6-4cee-b5ce-710b77c7bb0d',
        externalId: undefined,
        name: 'Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Target (text)
       *
       * Target URL - Set target URL including i.e. UTM parameters.
       */
      redirect_url: {
        codename: 'redirect_url',
        id: '701f593b-aca1-49d2-8810-1ac448ee16f0',
        externalId: undefined,
        name: 'Target',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '541b4fba-088a-4f59-9098-326eb7ff075c',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Milestone
   */
  milestone: {
    codename: 'milestone',
    id: '59d408cc-299b-48d2-972b-22028e095963',
    externalId: undefined,
    name: 'Milestone',
    elements: {
      /**
       * Subtitle (text)
       */
      subtitle: {
        codename: 'subtitle',
        id: '7b04ac84-cdd9-4e30-b4f6-93ace70f4116',
        externalId: undefined,
        name: 'Subtitle',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'f49769f4-7688-4fee-94e4-16174c03e049',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Navigation
   */
  navigation: {
    codename: 'navigation',
    id: '0959526f-414e-455f-8987-23f43caa198b',
    externalId: undefined,
    name: 'Navigation',
    elements: {
      /**
       * Caption (text)
       */
      caption: {
        codename: 'caption',
        id: '3c444b7e-7c75-4ad0-bde2-8843b1db8806',
        externalId: undefined,
        name: 'Caption',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * External link (text)
       *
       * Use when the navigation item points to an external URL.
       */
      external_link: {
        codename: 'external_link',
        id: 'ef922ba0-5943-424c-87da-d75b2a5fd757',
        externalId: undefined,
        name: 'External link',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Label (text)
       */
      label: {
        codename: 'label',
        id: '4a51541b-d628-459b-a558-d3f00a612bf4',
        externalId: undefined,
        name: 'Label',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Open in a new window (multiple_choice)
       */
      open_in_a_new_window: {
        codename: 'open_in_a_new_window',
        id: '9f607e0f-8baa-4028-81ee-e6c059847d5e',
        externalId: undefined,
        name: 'Open in a new window',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Page link (modular_content)
       *
       * Use to link navigation item to an internal page.
       */
      page_link: {
        codename: 'page_link',
        id: 'aaa302cf-7222-4e7b-8927-01fbec047a4f',
        externalId: undefined,
        name: 'Page link',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subitems (subpages)
       */
      subitems: {
        codename: 'subitems',
        id: 'ff306ed1-b5de-4f0f-85fd-b8548efc4c29',
        externalId: undefined,
        name: 'Subitems',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Product
   */
  product: {
    codename: 'product',
    id: 'd8195a31-dd83-402a-9fac-019c14978cb3',
    externalId: undefined,
    name: 'Product',
    elements: {
      /**
       * Product category (taxonomy)
       */
      category: {
        codename: 'category',
        id: '606496e4-acf4-423b-bf60-453dcd1e0ce7',
        externalId: undefined,
        name: 'Category',
        required: true,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: '74e64991-93d6-467f-84f9-d39b9b8b83f2',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Price (number)
       *
       * Price in Euros.
       */
      price: {
        codename: 'price',
        id: '0d215ac7-1c98-42ac-aec6-7f02ad4f34f9',
        externalId: undefined,
        name: 'Price',
        required: true,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * Product image (asset)
       */
      product_image: {
        codename: 'product_image',
        id: 'ec77bde2-a08a-4c91-9105-faf43a1899be',
        externalId: undefined,
        name: 'Product image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Slug (url_slug)
       */
      slug: {
        codename: 'slug',
        id: '0a75f346-deea-464b-a278-43d9c3bcc2b4',
        externalId: undefined,
        name: 'Slug',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '3a30f214-983b-4fd2-b72b-f7116d6040ca',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Rich text content
   */
  component___rich_text_content: {
    codename: 'component___rich_text_content',
    id: '7d315973-6157-4b4b-b722-0674b16121bf',
    externalId: undefined,
    name: 'Rich text content',
    elements: {
      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: 'f7e1a1d0-f3cb-42f8-b7b1-4005fae328d0',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Solution
   */
  component___solution: {
    codename: 'component___solution',
    id: '8cf1f294-22da-4ce9-8b9e-57e09d03c4d6',
    externalId: undefined,
    name: 'Solution',
    elements: {
      /**
       * Background image (asset)
       */
      background_image: {
        codename: 'background_image',
        id: '98e2f96d-556b-4c01-afa8-b613d3dc3bbc',
        externalId: undefined,
        name: 'Background image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Overview (rich_text)
       */
      overview: {
        codename: 'overview',
        id: '06bb2885-9c53-40b0-8429-c1f3b2ebb956',
        externalId: undefined,
        name: 'Overview',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '3fbe76f7-aef4-4336-8100-24f428a29ef8',
        externalId: undefined,
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Solution set
   */
  solution_set: {
    codename: 'solution_set',
    id: '1a1d2ce6-4a23-4428-acac-78205e9d72b5',
    externalId: undefined,
    name: 'Solution set',
    elements: {
      /**
       * Solutions (modular_content)
       */
      solutions: {
        codename: 'solutions',
        id: '90719e11-0830-477c-991a-93ac31e1cc5b',
        externalId: undefined,
        name: 'Solutions',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Testimonial
   */
  testimonial: {
    codename: 'testimonial',
    id: '05cc2616-b52e-4746-a5fe-9dfb04c80907',
    externalId: undefined,
    name: 'Testimonial',
    elements: {
      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: '6811e346-dc62-48e5-b138-a63cb7b34c99',
        externalId: undefined,
        name: 'Author',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Format (multiple_choice)
       *
       * Defines how the individual testimonial elements are organized.
       */
      format: {
        codename: 'format',
        id: '999d2af3-212d-4d5d-9348-5e14c3e9f957',
        externalId: undefined,
        name: 'Format',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Subtitle (text)
       */
      subtitle: {
        codename: 'subtitle',
        id: '1361ee48-656f-4f72-9c89-b9e8d3244085',
        externalId: undefined,
        name: 'Subtitle',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '08a335a9-fa58-455c-928c-df57e7402af5',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * UMLP component – Achievements
   */
  umlp_component___achievements: {
    codename: 'umlp_component___achievements',
    id: '6f83adaa-788a-4778-8ed6-b64d73d54cff',
    externalId: undefined,
    name: 'UMLP component – Achievements',
    elements: {
      /**
       * Achievements (modular_content)
       */
      achievements: {
        codename: 'achievements',
        id: '43fad747-0fac-4559-a0e4-9b1576eff9e7',
        externalId: undefined,
        name: 'Achievements',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * UMLP component – Resource listing
   */
  umlp_component___resource_listing: {
    codename: 'umlp_component___resource_listing',
    id: 'b6f5902d-8a00-494d-97dc-3bf99e3bf801',
    externalId: undefined,
    name: 'UMLP component – Resource listing',
    elements: {},
  },

  /**
   * Web spotlight root
   */
  web_spotlight_root: {
    codename: 'web_spotlight_root',
    id: '228de48c-ffb2-4b5e-862f-47e2c60e0c01',
    externalId: undefined,
    name: 'Web spotlight root',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: '94e31e00-81b8-4ab4-b17b-7d165ed3020e',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '61be1529-49fc-43b6-ba33-962a360e4c9f',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '9a340e66-9416-455e-8763-848a330a4b2e',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },
} as const;
