/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Migration test
 * Environment: Production
 * Project Id: b5905129-8bdb-0115-aca0-d1700790cd2a
 */
export const contentTypes = {
  /**
   * 💡 Page
   */
  page: {
    codename: 'page',
    id: '0cb81f69-3f4b-46a1-8ce2-0aada4cdc358',
    externalId: undefined,
    name: '💡 Page',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: '27bc37be-796c-4219-a85d-cd61fc2e4f43',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '0ae36299-95cb-54d7-9be9-7d76ee6f4be0',
        externalId: 'description-67490da2-0356-44cc-a7ed-e47afc5487a9',
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: 'a0f7ffe0-5e94-532f-a86e-d77761eb35af',
        externalId: 'keywords-2b4ba0dc-10f1-4da9-b559-3c374c45517d',
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '7e159b22-7b95-4a9b-9e2a-a79d407edd76',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'c2808c7e-9f57-4d0b-815c-f535752ed1cd',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: 'd278379c-9f60-58f8-92e0-0e665033dd95',
        externalId: 'title-897b2878-2b80-48ea-a328-16e25a384bb7',
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * URL (url_slug)
       */
      url: {
        codename: 'url',
        id: '434f911b-c645-46e1-a633-0c8a3b1e9207',
        externalId: undefined,
        name: 'URL',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 💡 Web spotlight root
   */
  web_spotlight_root: {
    codename: 'web_spotlight_root',
    id: 'eba96027-914d-48f7-a7f8-38502fa7e869',
    externalId: undefined,
    name: '💡 Web spotlight root',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: '0273c87b-86ae-4c9b-8e49-d064f25d1417',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '0ae36299-95cb-54d7-9be9-7d76ee6f4be0',
        externalId: 'description-67490da2-0356-44cc-a7ed-e47afc5487a9',
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: 'a0f7ffe0-5e94-532f-a86e-d77761eb35af',
        externalId: 'keywords-2b4ba0dc-10f1-4da9-b559-3c374c45517d',
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Navigation (modular_content)
       */
      navigation: {
        codename: 'navigation',
        id: 'a1a6b4d4-2f47-5071-aa53-1d283d2dee3e',
        externalId: 'navigation-23dd89bd-09c7-499f-a7b0-3c00d007cc83',
        name: 'Navigation',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: '9e2d4dd9-7d9f-4365-99e0-6b1528f25215',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'fba9369c-61f3-4a91-a809-70129484c3ca',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: 'd278379c-9f60-58f8-92e0-0e665033dd95',
        externalId: 'title-897b2878-2b80-48ea-a328-16e25a384bb7',
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },
    },
  },

  /**
   * 🧩 Callout
   */
  callout: {
    codename: 'callout',
    id: '72c5b04f-e316-5912-baf2-8ccd2f0ad7a2',
    externalId: 'callout-4a3b08ce-eb20-45bb-b4eb-5a9576d40ae4',
    name: '🧩 Callout',
    elements: {
      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '15a9fc79-e85f-5bb1-8e81-d0362cd93b93',
        externalId: 'content-0380c2b6-a9b4-4459-8a3e-56d3297a988a',
        name: 'Content',
        required: true,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Type (multiple_choice)
       */
      type: {
        codename: 'type',
        id: '44dd9032-c950-53b8-91bd-c6c586233311',
        externalId: 'type-bdd7f318-dc0b-40de-9d4f-ae5970cd2e26',
        name: 'Type',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Content chunk
   */
  content_chunk: {
    codename: 'content_chunk',
    id: '77194b36-3971-5137-b0d8-8dbed2b4b18a',
    externalId: 'contentChunk-1fb6ab30-d298-483e-b591-3c35602a4e8e',
    name: '🧱 Content chunk',
    elements: {
      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '7ace9f5a-cf40-5339-8122-2f320ba3326e',
        externalId: 'content-3326d741-fca1-4b84-80d8-e8b41d99b103',
        name: 'Content',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Hero unit
   */
  hero_unit: {
    codename: 'hero_unit',
    id: '3436c1cd-fb6f-596d-a812-918cc5cd1e7f',
    externalId: 'heroUnit-a8657b11-53f5-404f-98ac-c48e60e1e2ea',
    name: '🧱 Hero unit',
    elements: {
      /**
       * Background image (asset)
       */
      background_image: {
        codename: 'background_image',
        id: '688b3d35-b23c-5e2e-a183-57c0651e2161',
        externalId: 'backgroundImage-78552164-1817-4a34-8efc-141283d1224a',
        name: 'Background image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Fact (modular_content)
       */
      fact: {
        codename: 'fact',
        id: '170f10ce-8d2f-5594-aa09-e4d0cb1996e8',
        externalId: 'fact-f96cd17a-d640-44e7-98dd-9288f703dcc0',
        name: 'Fact',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Target (text)
       */
      target: {
        codename: 'target',
        id: '8ca0ee74-9553-52f8-a103-236e5397ff11',
        externalId: 'target-f8b0bae5-a033-47bf-9c81-9b10e51e7c78',
        name: 'Target',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Navigation
   */
  navigation: {
    codename: 'navigation',
    id: '08ad03e2-c164-56e7-9903-52f615e8ec82',
    externalId: 'navigation-881cf5d2-49ce-429d-98bc-128a94928ccc',
    name: '🧱 Navigation',
    elements: {
      /**
       * Caption (text)
       */
      caption: {
        codename: 'caption',
        id: '1504c067-40bf-5efd-b5c9-88f5ff2fe5a5',
        externalId: 'caption-deadf73e-6783-40f4-a56b-3328297728ea',
        name: 'Caption',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * External Link (text)
       *
       * Use when the navigation item points to an external URL.
       */
      external_link: {
        codename: 'external_link',
        id: '117e0dd9-c73f-59df-81dc-c3dfaf1155af',
        externalId: 'externalLink-a5b1f97c-4af7-4866-8bc0-3d971f260794',
        name: 'External Link',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Label (text)
       */
      label: {
        codename: 'label',
        id: '1eb29cfa-1eba-5855-8fb9-09bc7e32dcba',
        externalId: 'label-7dea416d-4ba8-44f2-a672-f928ccb63d00',
        name: 'Label',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Open in a new window (multiple_choice)
       */
      open_in_a_new_window: {
        codename: 'open_in_a_new_window',
        id: '6b4e2db2-9624-50b2-8aff-64f9a070e442',
        externalId: 'openInANewWindow-ac4215ca-7e51-4e16-8d6c-41895f0557d5',
        name: 'Open in a new window',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Page Link (modular_content)
       *
       * Use to link navigation item to an internal page.
       */
      page_link: {
        codename: 'page_link',
        id: 'b59af59b-0db1-5b7c-a92e-69f225b52b8c',
        externalId: 'pageLink-454b1c38-a71b-4610-88ec-746aa2a80aad',
        name: 'Page Link',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subitems (modular_content)
       */
      subitems: {
        codename: 'subitems',
        id: '2a2104ce-cb8d-5d6b-a90f-a78183efc478',
        externalId: 'subItems-de543313-edb7-4fd5-9682-3c424e4ed0d4',
        name: 'Subitems',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * 🧱 Visual container
   */
  _visual_container: {
    codename: '_visual_container',
    id: 'e23c2808-d953-5914-a526-ab702cc519f5',
    externalId: 'visualContainer-acc53fbf-9b9f-4a46-b8f5-26c3df8b4a72',
    name: '🧱 Visual container',
    elements: {
      /**
       * Items (modular_content)
       */
      items: {
        codename: 'items',
        id: '081f63c6-9589-5f8d-a9de-bc3b1ceb24e7',
        externalId: 'items-b445a138-71a4-40e4-a3dd-6c38eeeb480e',
        name: 'Items',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subtitle (text)
       */
      subtitle: {
        codename: 'subtitle',
        id: 'db1dcba9-ffde-5ff9-a8dc-e594cf3d27d8',
        externalId: 'subTitle-6e3e636e-e6c1-4663-9bcc-aeb303bc5342',
        name: 'Subtitle',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '22e19c4d-aeeb-5c87-852c-b8a8202dfbad',
        externalId: 'title-b1927504-dd90-4375-b8f4-688cc2a3aca1',
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Visual representation (multiple_choice)
       *
       * ⚠ You should try to avoid including visual information in the content. This is one of the edge cases that might be viable since this content type is used for website representation only.
       */
      visual_representation: {
        codename: 'visual_representation',
        id: '2c3d8fe4-a21d-524a-aba5-5fd1913f8341',
        externalId: 'visualRepresentation-da31aeea-3a42-4f1b-b46f-32e0b8d7fd06',
        name: 'Visual representation',
        required: true,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Article
   */
  article: {
    codename: 'article',
    id: '5568750a-d7fd-51fa-a8bb-a08940ac5395',
    externalId: 'article-f3f94d06-ce91-42b5-ad0b-3827e02653af',
    name: 'Article',
    elements: {
      /**
       * Abstract (text)
       *
       * Don't make it too long. At this point users decides, whether they want to continue reading!
       */
      abstract: {
        codename: 'abstract',
        id: '5ae9979f-cc84-5c0b-81d8-65eabf11f2ec',
        externalId: 'abstract-89139239-2ea2-4789-a3b7-aace73a9914d',
        name: 'Abstract',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Article type (taxonomy)
       */
      article_type: {
        codename: 'article_type',
        id: 'c505fded-9c1f-5583-8cf2-dfa4763d2f2a',
        externalId: 'articleType-cb380e8d-da66-40df-98d2-30e50e3df4e9',
        name: 'Article type',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: '5be60600-49ac-52f8-a759-ab0ead3a3301',
        externalId: 'author-aac99d24-3659-400b-96c7-8bf132177ab2',
        name: 'Author',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Content (rich_text)
       */
      content: {
        codename: 'content',
        id: '7d4b95b0-76fc-552e-8931-c90dd2746399',
        externalId: 'content-85bdaa99-d54f-4d43-be28-58c48f7b5dd8',
        name: 'Content',
        required: true,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '0ae36299-95cb-54d7-9be9-7d76ee6f4be0',
        externalId: 'description-67490da2-0356-44cc-a7ed-e47afc5487a9',
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Hero Image (asset)
       */
      hero_image: {
        codename: 'hero_image',
        id: 'ed868ae7-0b90-5752-a53b-aa4cfa2ca56e',
        externalId: 'heroImage-890b7b02-d4ae-4ad9-ad8f-ad6d2d44b27c',
        name: 'Hero Image',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: 'a0f7ffe0-5e94-532f-a86e-d77761eb35af',
        externalId: 'keywords-2b4ba0dc-10f1-4da9-b559-3c374c45517d',
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Publishing date (date_time)
       */
      publishing_date: {
        codename: 'publishing_date',
        id: 'dba8efd9-052c-557a-9dfd-3f43f966eab8',
        externalId: 'publishingDate-1a33b696-88a9-4d15-8698-a617f6c908c5',
        name: 'Publishing date',
        required: true,
        type: 'date_time',
        snippetCodename: undefined,
      },

      /**
       * Slug (url_slug)
       */
      slug: {
        codename: 'slug',
        id: '7b9f3bb2-2efb-5285-8988-bfb66e45cf77',
        externalId: 'slug-b2b11773-ce44-4a09-8306-2888fa55a6b6',
        name: 'Slug',
        required: true,
        type: 'url_slug',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       *
       * You can use online tools get score on your titles and incrementally improve it.
       */
      title: {
        codename: 'title',
        id: 'ae9be828-90fe-5fb4-ae3a-8dfe047e2567',
        externalId: 'title-862e8b39-b10b-4448-9da3-cbb3f07378d1',
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: 'd278379c-9f60-58f8-92e0-0e665033dd95',
        externalId: 'title-897b2878-2b80-48ea-a328-16e25a384bb7',
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },
    },
  },

  /**
   * Fact
   */
  fact: {
    codename: 'fact',
    id: 'df18210c-bacd-5980-81a7-b35c2a66d81f',
    externalId: 'fact-e5a475ac-8957-480b-a42b-2dc711cbb3b8',
    name: 'Fact',
    elements: {
      /**
       * Image (asset)
       */
      image: {
        codename: 'image',
        id: '8c8946ce-e683-5df1-b029-967a3e43e056',
        externalId: 'image-c64dc899-8efa-4ce9-8134-3f430856b712',
        name: 'Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Message (text)
       */
      message: {
        codename: 'message',
        id: 'db8a7f6b-afd5-5170-bd6f-e450a96c8053',
        externalId: 'message-82b47f3d-76e7-46fd-9fa0-692a3b8917d6',
        name: 'Message',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '75c5ed43-3eb7-5902-bf8b-4ddf8f830c8b',
        externalId: 'title-3bd73b39-da80-4ecf-8a53-4972b39df0e4',
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Person
   */
  person: {
    codename: 'person',
    id: '3b8aea57-afdc-55b4-b7aa-30991e2515f8',
    externalId: 'person-94147fa7-c60f-4a80-bee9-9efeaae9f858',
    name: 'Person',
    elements: {
      /**
       * Bio (rich_text)
       */
      bio: {
        codename: 'bio',
        id: '4341b423-f053-523f-bd0f-b63b6c786532',
        externalId: 'bio-769f658c-cb5a-48ea-8c0c-337647e5ed7b',
        name: 'Bio',
        required: false,
        type: 'rich_text',
        snippetCodename: undefined,
      },

      /**
       * First Name (text)
       */
      first_name: {
        codename: 'first_name',
        id: '412e6d34-62aa-524a-b97f-a23b2cf3e252',
        externalId: 'firstName-3a93ab33-5d97-4c00-b26d-02d8cf178a1f',
        name: 'First Name',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Last Name (text)
       */
      last_name: {
        codename: 'last_name',
        id: '3b153753-6cd6-58e8-99ae-e60020ffd890',
        externalId: 'lastName-35d83aef-7b5b-4ae3-98f4-73710ff01473',
        name: 'Last Name',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Occupation (text)
       */
      occupation: {
        codename: 'occupation',
        id: 'd73579bd-b03a-59e0-8464-63939e0cb6c7',
        externalId: 'occupation-ae875fe0-0192-4220-95b4-1d48dc2a3cd2',
        name: 'Occupation',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Photograph (asset)
       */
      photograph: {
        codename: 'photograph',
        id: '514655d3-a35d-5c58-8807-b62108651728',
        externalId: 'photograph-fba5b46b-5052-4ed8-b405-bdc08af6b3d6',
        name: 'Photograph',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Product
   */
  product: {
    codename: 'product',
    id: '28f3a148-bcdd-5a1a-b821-d54b2a94dabd',
    externalId: 'product-3c55cfb7-aaf8-47a6-8c47-b7b43bd50ca5',
    name: 'Product',
    elements: {
      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: '283ff3b9-c4c5-511b-bb4b-50cf94b827bc',
        externalId: 'description-90141638-10c1-435e-928c-3c9b3d5bceea',
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Description (text)
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '0ae36299-95cb-54d7-9be9-7d76ee6f4be0',
        externalId: 'description-67490da2-0356-44cc-a7ed-e47afc5487a9',
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: 'a0f7ffe0-5e94-532f-a86e-d77761eb35af',
        externalId: 'keywords-2b4ba0dc-10f1-4da9-b559-3c374c45517d',
        name: 'Keywords',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },

      /**
       * Price (number)
       *
       * Price in Euros. ⚠️ Price element is here just for an illustration and should no be in production projects.
       */
      price: {
        codename: 'price',
        id: '07b0eeae-1a51-5414-a6f9-0ddbb2e8e21a',
        externalId: 'price-ba493716-6317-4184-b5bc-085c40a63944',
        name: 'Price',
        required: true,
        type: 'number',
        snippetCodename: undefined,
      },

      /**
       * Product category (taxonomy)
       */
      product_category: {
        codename: 'product_category',
        id: '5dac4e43-bea4-5373-b628-4006485b87a7',
        externalId: 'category-006b0b49-a667-4c5e-a2f0-25e0acaa3146',
        name: 'Product category',
        required: true,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * Product image (asset)
       *
       * Use images with no background if possible.
       */
      product_image: {
        codename: 'product_image',
        id: '502b68a2-2d68-512a-b1f0-460c8bc38fe6',
        externalId: 'productImage-29116c9e-2c55-490f-8726-8b4494af1fbe',
        name: 'Product image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Slug (url_slug)
       */
      slug: {
        codename: 'slug',
        id: 'cb72527a-b7c5-5591-9a80-8415a799d4a6',
        externalId: 'slug-00ac4349-6d09-4b2f-9cf9-e90b5e19a2ff',
        name: 'Slug',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '599d56c3-0840-5967-a869-1d41419775a4',
        externalId: 'title-aec8f49f-6f4a-4bde-90e0-055fe0636847',
        name: 'Title',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: 'd278379c-9f60-58f8-92e0-0e665033dd95',
        externalId: 'title-897b2878-2b80-48ea-a328-16e25a384bb7',
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: 'seo_metadata',
      },
    },
  },

  /**
   * Testimonial
   */
  testimonial: {
    codename: 'testimonial',
    id: 'e3abca52-cc79-5b7d-821d-83f873e0a7ba',
    externalId: 'testimonial-dffc4fb9-48e6-4dd5-a523-9909a8aad03d',
    name: 'Testimonial',
    elements: {
      /**
       * Author (modular_content)
       */
      author: {
        codename: 'author',
        id: 'b2760eb7-dd96-57dd-a6c4-25d01a756947',
        externalId: 'author-d0280809-d463-4002-950c-3d740233094c',
        name: 'Author',
        required: true,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Quote (text)
       */
      quote: {
        codename: 'quote',
        id: '955350b6-558a-5dcf-90c1-06d946fb90a0',
        externalId: 'quote-d2cf56c9-b6ca-4c84-a2f1-462cb00a8b9a',
        name: 'Quote',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: 'e2b74907-fbc1-5fee-bb25-ef726b232b5e',
        externalId: 'title-0e4a5c2e-44f8-4ea7-bfa3-489daf8493ec',
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },
} as const;
