/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: New sample project
 * Environment: Production
 * Project Id: 2cedc519-a547-01ba-dde7-b01e00b909a1
 */
export const contentTypeSnippets = {} as const;
