/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Ficto Healthtech
 * Environment: Production
 * Project Id: 0a12060e-20af-0124-a95d-871d26379561
 */
export const contentTypeSnippets = {
  /**
   * 💡 Emoji guideline
   */
  _web_spotlight_root: {
    codename: '_web_spotlight_root',
    id: 'c0e99be6-4a78-4f1b-954e-93793109c67e',
    externalId: undefined,
    name: '💡 Emoji guideline',
    elements: {},
  },

  /**
   * 🧩 Emoji guideline
   */
  _emoji_guideline: {
    codename: '_emoji_guideline',
    id: '590e3d38-a5d6-46ab-a3a1-1cc47869c34a',
    externalId: undefined,
    name: '🧩 Emoji guideline',
    elements: {},
  },

  /**
   * 🧱 Emoji guideline
   */
  emoji_guideline: {
    codename: 'emoji_guideline',
    id: '09485dd4-6af3-4483-8e3a-8ab6a83743ed',
    externalId: undefined,
    name: '🧱 Emoji guideline',
    elements: {},
  },

  /**
   * SEO Metadata
   */
  seo_metadata: {
    codename: 'seo_metadata',
    id: '22775c9b-d269-4b03-941f-8dc0ee6c00c0',
    externalId: undefined,
    name: 'SEO Metadata',
    elements: {
      /**
       * Title (text)
       */
      seo_metadata__title: {
        codename: 'seo_metadata__title',
        id: '661a085e-eb93-437d-9f97-b58a1ec256af',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
      },

      /**
       * Description (text)
       */
      seo_metadata__description: {
        codename: 'seo_metadata__description',
        id: '0848a00d-f935-4270-b9b5-ba0b22d7eaa2',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
      },

      /**
       * Keywords (text)
       */
      seo_metadata__keywords: {
        codename: 'seo_metadata__keywords',
        id: 'ee4b0220-7852-4738-84a4-825b0c8b4284',
        externalId: undefined,
        name: 'Keywords',
        required: false,
        type: 'text',
      },
    },
  },
} as const;
