/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Welltale Cosmetics, Inc
 * Environment: Live
 * Project Id: d4250b5b-747a-004f-06cd-bef9e9b24150
 */
export const languages = {
  /**
   * English (United States)
   */
  enUS: {
    codename: 'en-US',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'English (United States)',
  },

  /**
   * Spanish (Spain)
   */
  esES: {
    codename: 'es-ES',
    id: 'd1f95fde-af02-b3b5-bd9e-f232311ccab8',
    isActive: true,
    isDefault: false,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Spanish (Spain)',
  },
} as const;
