/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: HealthTech
 * Environment: New Production
 * Project Id: 0a12060e-20af-0124-a95d-871d26379561
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    isActive: true,
    isDefault: true,
    fallbackLanguageId: '00000000-0000-0000-0000-000000000000',
    externalId: undefined,
    name: 'Default project language',
  },
} as const;
