/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: HealthTech
 * Environment: New Production
 * Project Id: 0a12060e-20af-0124-a95d-871d26379561
 */
export const roles = {} as const;
