/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Empty-migration-testing-project
 * Environment: Production
 * Project Id: 77e9b818-c4a5-01cd-d590-4cdb72cd5875
 */
export const taxonomies = {
  /**
   * Article type
   */
  article_type: {
    codename: 'article_type',
    id: '02c148a3-4536-587d-aabd-8ac2ae6557c7',
    externalId: 'articleType-7fbd6882-2a33-40a3-9aec-ad1547655cc8',
    name: 'Article type',
    terms: {
      blog_post: {
        codename: 'blog_post',
        id: 'e986f215-f1f3-59af-bdc9-a1ecde9d654b',
        externalId: 'post-d55709dc-6a01-4edd-a52e-57465ae29e8f',
        name: 'Blog post',
        terms: {},
      },
      industry_news: {
        codename: 'industry_news',
        id: 'ba02e54f-dcfb-5f03-8a7b-1a7441d28cb7',
        externalId: 'industryNews-4abee914-15e7-4a63-88dd-1387fb33400a',
        name: 'Industry news',
        terms: {},
      },
    },
  },

  /**
   * Surgical products category
   */
  surgical_products_category: {
    codename: 'surgical_products_category',
    id: '70a6b135-42e7-56ae-a15a-dfa8119455f5',
    externalId: 'surgicalProductCategory-0c888f24-363c-4c63-986c-829cdfeabe17',
    name: 'Surgical products category',
    terms: {
      cutting: {
        codename: 'cutting',
        id: 'aa71e496-39e3-53a2-b863-b1a2065f3b1c',
        externalId: 'cutting-295b891d-2a12-4eb5-865a-f0e69d83bf51',
        name: 'Cutting',
        terms: {},
      },
      grasping: {
        codename: 'grasping',
        id: '0a8d0fa0-a2ae-572c-a8d4-6565c3695e41',
        externalId: 'grasping-2e8d3577-943e-49ff-84c5-e5fc7d089bc6',
        name: 'Grasping',
        terms: {},
      },
      retracting: {
        codename: 'retracting',
        id: '669aa64b-d06a-5643-85b8-52537d5a3250',
        externalId: 'retracting-5c6a29b7-f7db-4a73-a007-145914825681',
        name: 'Retracting',
        terms: {
          hand_held: {
            codename: 'hand_held',
            id: 'b202127d-de50-543b-9b10-975a3502df17',
            externalId:
              'handHeldRetracting-d9dfadd1-ae67-4b38-96bc-d0e2a59d9cfb',
            name: 'Hand held',
            terms: {},
          },
          self_retaining: {
            codename: 'self_retaining',
            id: '5375192e-e468-5161-9f1e-2e118aebdc2b',
            externalId:
              'selfRetainingRetracting-6847a080-cf49-4826-99c0-98d4889a1124',
            name: 'Self retaining',
            terms: {},
          },
        },
      },
    },
  },
} as const;
