/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Ficto Healthtech
 * Environment: New Production
 * Project Id: 0a12060e-20af-0124-a95d-871d26379561
 */
export const taxonomies = {
  /**
   * Article type
   */
  article_type: {
    codename: 'article_type',
    id: '7328c36a-d608-41eb-b640-71f7ac9bcd27',
    externalId: undefined,
    name: 'Article type',
    terms: {
      case_study: {
        codename: 'case_study',
        id: 'ae6e1aaf-b997-4879-a7b8-05bdb0d5a87f',
        externalId: undefined,
        name: 'Case study',
        terms: {},
      },
      clinical_trial: {
        codename: 'clinical_trial',
        id: 'dc9f8f81-7a43-4a59-a67c-5eaa60dd2396',
        externalId: undefined,
        name: 'Clinical trial',
        terms: {},
      },
      industry_news: {
        codename: 'industry_news',
        id: '08981170-0142-4e1d-8448-03a5ba1f5bee',
        externalId: undefined,
        name: 'Industry news',
        terms: {},
      },
      research: {
        codename: 'research',
        id: 'dc3b3736-b090-47a3-86e2-1dd1618f7e83',
        externalId: undefined,
        name: 'Research',
        terms: {},
      },
    },
  },

  /**
   * Product category
   */
  product_category: {
    codename: 'product_category',
    id: 'e70e602f-49c6-4980-a748-5a6263d366c5',
    externalId: undefined,
    name: 'Product category',
    terms: {
      machinery: {
        codename: 'machinery',
        id: 'd9d5bed9-a7d6-4b74-ab05-c5a063df56fe',
        externalId: undefined,
        name: 'Machinery',
        terms: {},
      },
      other: {
        codename: 'other',
        id: '1174cd78-c6d2-4965-93c5-af17f535dadf',
        externalId: undefined,
        name: 'Other',
        terms: {},
      },
      precision_instruments: {
        codename: 'precision_instruments',
        id: 'd3418351-c394-4fa7-8364-312dc706779e',
        externalId: undefined,
        name: 'Precision instruments',
        terms: {},
      },
      sanitary_clothing: {
        codename: 'sanitary_clothing',
        id: 'f8638c49-3e84-412d-b798-71f444b3168b',
        externalId: undefined,
        name: 'Sanitary clothing',
        terms: {},
      },
    },
  },
} as const;
