/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Ficto Healthtech [QA Source project]
 * Environment: DanielP: Development
 * Project Id: 423ac17f-a20e-001f-3d73-6e446bf72c72
 */
export const webhooks = {} as const;
