/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Empty-migration-testing-project
 * Environment: Production
 * Project Id: 77e9b818-c4a5-01cd-d590-4cdb72cd5875
 */
export const webhooks = {} as const;
