/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: New sample migrations (TMP) (Kontent)
 * Environment: App test
 * Project Id: 89962bec-344a-01fd-58aa-40c92b21f579
 */
export const workflows = {
  /**
   * Default
   * Archived step Id: 7a535a69-ad34-47f8-806a-def1fdf4d391
   * Published step Id: c199950d-99f0-4983-b711-6c4c91624b22
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
